export interface Inspection {
  id?: string;
  userId?: string;
  yearFMCSA: string;
  FMCSA: string;
  yearBIT: string;
  BIT: string;
  licenseNumber: string;
  state: string;
  location: string;
  quipment: string;
  ownerOrLessor: string;
  ok1: string;
  repair1: string;
  labor1: string;
  material1: string;
  ok2: string;
  repair2: string;
  labor2: string;
  material2: string;
  ok3: string;
  repair3: string;
  labor3: string;
  material3: string;
  ok4: string;
  repair4: string;
  labor4: string;
  material4: string;
  ok5: string;
  repair5: string;
  labor5: string;
  material5: string;
  ok6: string;
  repair6: string;
  labor6: string;
  material6: string;
  ok7: string;
  repair7: string;
  labor7: string;
  material7: string;
  ok8: string;
  repair8: string;
  labor8: string;
  material8: string;
  ok9: string;
  repair9: string;
  labor9: string;
  material9: string;
  ok10: string;
  repair10: string;
  labor10: string;
  material10: string;
  ok11: string;
  repair11: string;
  labor11: string;
  material11: string;
  ok12: string;
  repair12: string;
  labor12: string;
  material12: string;
}

export interface InspectionError {
  yearFMCSA: string;
  FMCSA: string;
  yearBIT: string;
  BIT: string;
  licenseNumber: string;
  state: string;
  location: string;
  quipment: string;
  ownerOrLessor: string;
}

export const initInspection = (): Inspection => ({
  yearFMCSA: "",
  FMCSA: "",
  yearBIT: "",
  BIT: "",
  licenseNumber: "",
  state: "",
  location: "",
  quipment: "",
  ownerOrLessor: "",
  ok1: "",
  repair1: "",
  labor1: "",
  material1: "",
  ok2: "",
  repair2: "",
  labor2: "",
  material2: "",
  ok3: "",
  repair3: "",
  labor3: "",
  material3: "",
  ok4: "",
  repair4: "",
  labor4: "",
  material4: "",
  ok5: "",
  repair5: "",
  labor5: "",
  material5: "",
  ok6: "",
  repair6: "",
  labor6: "",
  material6: "",
  ok7: "",
  repair7: "",
  labor7: "",
  material7: "",
  ok8: "",
  repair8: "",
  labor8: "",
  material8: "",
  ok9: "",
  repair9: "",
  labor9: "",
  material9: "",
  ok10: "",
  repair10: "",
  labor10: "",
  material10: "",
  ok11: "",
  repair11: "",
  labor11: "",
  material11: "",
  ok12: "",
  repair12: "",
  labor12: "",
  material12: "",
});

export const initInspectionError = (): InspectionError => ({
  yearFMCSA: "",
  FMCSA: "",
  yearBIT: "",
  BIT: "",
  licenseNumber: "",
  state: "",
  location: "",
  quipment: "",
  ownerOrLessor: "",
});
