const services = [
  { code: "", description: "Resecure Bulk head fitting" },
  { code: "", description: "Replace ABS Sensor -  Left Front" },
  { code: "", description: "Replace ABS Sensor -  Left  Rear" },
  { code: "", description: "Replace ABS Sensor -  Right Front" },
  { code: "", description: "Replace ABS Sensor -  Right Rear" },
  { code: "", description: "Refasten  ABS harness Cable with zip tie" },
  { code: "", description: "Check ABS System" },
  { code: "", description: "Straight Mudflap Bracket" },
  { code: "", description: "Repair Genset" },
  { code: "", description: "Roadability Inspection" },
  { code: "", description: "Service After Hour" },
  { code: "", description: "Replace  Laminated Flooring 1 Ft" },
  { code: "", description: "Paint Stencil" },
  { code: "", description: "Replace Slider lock Box" },
  { code: "", description: "resecure" },
  { code: "", description: "Roadability Inspection \n Adjust Brakes" },
  { code: "", description: "Repair Hostler" },
  { code: "", description: "Grease and Lubrication" },
  { code: "", description: "Finance Charges on Overdue Balance" },
  { code: "", description: "Resecure Push Rod Nut - Loose" },
  { code: "", description: "Replace Bulk Head Fitting" },
  { code: "", description: "Replace Gladhand Seal" },
  { code: "", description: "Re-Secure Gladhand" },
  { code: "", description: "Replace Gladhand Service" },
  { code: "", description: "Bulkhead Resecure Bulkhead Fitting Loose" },
  { code: "", description: "Replace Air Replace Air Line 3/8" },
  { code: "", description: "Replace Air Line 1/2" },
  { code: "", description: "Replace Bulkhead Fitting and Gladhand" },
  { code: "", description: "Replace 1 Brake Hose 4' With Swivels" },
  { code: "", description: "Replace Air hose and fitting" },
  { code: "", description: "Replace Air Fitting" },
  { code: "", description: "Replace Relay Air Valve" },
  { code: "", description: "Replace Air Tank W/ Brackets" },
  { code: "", description: "Weld Air Tank Brackets" },
  { code: "", description: "Replace Relay Valve 2 Ports" },
  { code: "", description: "Replace Relay Valve 4 Ports." },
  { code: "", description: "Replace Air Valve 4 Ports" },
  { code: "", description: "Refasten Air Line" },
  {
    code: "",
    description: "Tighten Air / Electrical Lines up to 5 per Jam Nuts.",
  },
  { code: "", description: "Remove + Clean Air Valve + Reinstall." },
  { code: "", description: "Adjust ABS Sensor (1 Axle)." },
  { code: "", description: "Adjust ABS Sensor (2 Axle)." },
  { code: "", description: "Straighten Push Rod" },
  { code: "", description: "Replace Slack Adjuster Manual" },
  { code: "", description: "Replace Slack Adjuster Automatic." },
  { code: "", description: "Free Up Slack Adjuster." },
  { code: "", description: "Free Up Slack Adjuster Additional." },
  { code: "", description: "Replace Brake Drum w/o Wheel Work." },
  { code: "", description: "Replace Brake Drum with Wheel Work." },
  {
    code: "",
    description:
      "Replace Brakes Shoes ( Each Wheel). Replace Hardware Kit\n Replace Seal-Stemco. Repack Bearing and Hub",
  },
  { code: "", description: "Replace Brake Shoe with Hardware kit." },
  { code: "", description: "Replace Brake Chamber bracket" },
  {
    code: "",
    description:
      "Removed Wheel + Replace Hardware Kit (Missing ) and Reinstall.",
  },
  { code: "", description: "Replace Wheel Seal" },
  {
    code: "",
    description:
      "Replace wheel seal\n Convert hub wheel from oil to grease\n Repack bearings \n Refill hub with grease",
  },
  {
    code: "",
    description:
      "Replace  Brakes Shoes Hardware Kit - Missing\r\n Replace Wheel Seal \r\n Repack Bearings ,Hub and Hubcap",
  },
  { code: "", description: "REPLACE BEARING AND RACES" },
  { code: "", description: "REPLACE BEARING AND RACES W/ WHEEL WORK" },
  {
    code: "",
    description:
      "Replace Hub Wheel 5 Spoke + Brake Drum +  Seal + Repack Bearings + Hubcap Gasket \r\nRepack with new Grease",
  },
  {
    code: "",
    description:
      "Replace  Hub Wheel (5 Spoke) +\r\n Repack Bearings\r\n Repack Hub Wheel with Grease \r\n Replace Hubcap Gasket \r\n Replace Seal",
  },
  { code: "", description: "FILL ALL NEW HUBS W/ NEW OIL" },
  { code: "", description: "FREE UP BRAKE SHOES (1) AXLE" },
  { code: "", description: "Repair  Air Hose - Leaking" },
  { code: "", description: "RESECURE AIR LINES AND HARNESS WIRE WITH ZIPTIE" },
  {
    code: "",
    description: "Replace air Hoses Clamps - Broken/Missing ( each clamp)",
  },
  { code: "", description: "Resecure Air Lines and Electrical Harness" },
  {
    code: "",
    description: "Replace ABS sensor + Replace Seal + Repack Bearings",
  },
  { code: "", description: "Replace Scam Bushing" },
  { code: "", description: "Trace + Repair Air system - Leaking" },
  {
    code: "",
    description: "Replace Abs sensor\r\n Resecure Abs Sensor with zip tie",
  },
  { code: "", description: "Replace Air Hoses Plastic Spacer" },
  { code: "", description: "Jack Up Wheel   and Check Play Bearing" },
  { code: "", description: "Replace Scam Bushing" },
  {
    code: "",
    description:
      "Replace Hub spoke wheel\r\n Replace Brake Drum \r\n Replace Brakes Shoes \r\n Replace Bearings and Races \r\n Replace 1 Seal \r\n Removed Old Bearing of Spindle - Frozen\r\n Repack with grease Bearings and Hub\r\n Retrack spindle and Replace Protorque Nut- Damage",
  },
  {
    code: "",
    description:
      "Trace + Repair Abs Problem \r\n Replace ABS Computer \r\n Replace 2 ABS Sensors",
  },
  { code: "", description: "Replace  Drain Cock Valve   Tank" },
  {
    code: "",
    description:
      "Replace Brakes Drum\r\n Replace Brakes Shoes \r\n Replace Hub /5 Spoke Wheel\r\n Replace Hubcap + Gasket \r\n Repack Bearings and Hub\r\n Replace Wheel Seal\r\n Replace Hardware Kit\r\n Replace Bearings",
  },
  {
    code: "",
    description:
      "Removed Air Valve + Replace Union Fitting + Reinstall Air Valve",
  },
  { code: "", description: "Resecure Air Valve - Leaking" },
  {
    code: "",
    description:
      "Replace Brakes Shoes \nReplace Brake Drum \nReplace wheel Seal\nReplace Hubcap + Gasket \nRepack Bearings",
  },
  {
    code: "",
    description:
      "Replace Bearing and Races\n Replace Wheel Seal \n Replace Hubcap , gasket , bolts and nuts \n Refill Oil",
  },
  { code: "", description: "Resecure Hub cap - Leaking" },
  {
    code: "",
    description:
      "Replace Brakes Shoes \n Replace Brake Drum \n Replace Bearing and Races \n Replace Seal \n Repack Bearings and Hub\n Replace Hubcap Gasket",
  },
  { code: "", description: "Replace  Suspension spring + U-Bolt  Kit" },
  {
    code: "",
    description: "Replace Hubcap +  Gasket and Refill Oil   34-49 Stemco",
  },
  {
    code: "",
    description:
      "Replace Abs Cable extension (Computer to Sensor) and Resecure with Zip tie.",
  },
  { code: "", description: "Resecure Hubcap + Clean" },
  { code: "", description: "Replace Hub Cap Gasket and Refill with Oil" },
  { code: "", description: "Trace + Repair ABS problem" },
  { code: "", description: "Replace ICC Bumper Horizontal (Channel)" },
  { code: "", description: "Replace Brake Drum" },
  { code: "", description: "Replace Spindle Nuts Large /Small and Lock Ring" },
  { code: "", description: "Check and  Adjust Brakes" },
  { code: "", description: "Resecure Bulk head and Fitting." },
  { code: "", description: "Replace Brake Chamber" },
  { code: "", description: "Replace Brake Chamber Clevis" },
  { code: "", description: "Tighten Bolt (s) Left , Right ICC Upright (s)" },
  {
    code: "",
    description: "Replace Hub wheel  lugnuts and nuts  ( each wheel )",
  },
  {
    code: "",
    description: "Replace Brakes Shoes \r\n Replace Hardware Kit",
  },
  {
    code: "",
    description: "Free up Scam Bushing - Frozen and Slack Adjuster ( each)",
  },
  { code: "", description: "Replace Gladhand Bracket Mount" },
  { code: "", description: "Replace Hubcap + Gasket and Refill with Gear Oil" },
  { code: "", description: "Free Up Scam Bushing and Slack Adjuster by Wheel" },
  { code: "", description: "Replace Slack Adjuster Automatic" },
  {
    code: "",
    description: "Resecure  / Refasten  Air Hoses with plastic Zip tie",
  },
  {
    code: "",
    description:
      "Resecure / Refasten  Air Hoses with Plastic Spacer   45137  3/8X3/8",
  },
  {
    code: "",
    description: "Replace Brake Drum + Replace Brakes Shoes +Hardware Kit",
  },
  { code: "", description: "Refasten Air Tank" },
  { code: "", description: "Refasten Air Bag Valve Bracket" },
  { code: "", description: "Replace Relay Air Valve SL1136" },
  { code: "", description: "Refasten Air Fitting" },
  { code: "", description: "Check and Adjust Brakes" },
  { code: "", description: "Reinstall Bulk Head Fitting and Gladhand" },
  {
    code: "",
    description:
      "Replace Air Hoses Support Spring  - Spring Slider  \n Haldex Spring airline support - 1163",
  },
  { code: "", description: "Resecure / Refasten Gladhand Holder Plate" },
  { code: "", description: "Replace Brake Chamber Dust Plug" },
  { code: "", description: "Replace Valve Drain Cock - Air Tank" },
  { code: "", description: "Refasten / Resecure Gladhand" },
  { code: "", description: "Replace Air Line Fitting" },
  { code: "", description: "Replace Air Hose Fitting" },
  { code: "", description: "Replace Brakes Shoes and Hardware Kit" },
  { code: "", description: "Replace Absorber Shock" },
  { code: "", description: "Trace and Repair Air Leak" },
  {
    code: "",
    description:
      "Jack Up and Check Wheel Bearing   (each wheel)\n Removed Hubcap and Retorque Nuts",
  },
  { code: "", description: "Replace Air Valve  Release Kit" },
  { code: "", description: "Removed and Reinstall Gladhand" },
  { code: "", description: "Resecure Push Rod Nut" },
  { code: "", description: "Free up Gladhand Swing Away" },
  { code: "", description: "Replace Slack Adjuster Manual" },
  { code: "", description: "Replace  Sloan Gladhand Shut-Off  -" },
  { code: "", description: "Removed and Reinstalled Gladhand Mounting Plate" },
  { code: "", description: "Replace Air Hose with 2 Fittings" },
  {
    code: "",
    description: "Resecure  / Refasten Gladhand + Bulk Head Fitting",
  },
  { code: "", description: "Replace 1/2 Female Ball Valve  2 way" },
  { code: "", description: "Replace Air Valve Pressure Protection 955417" },
  { code: "", description: "Replace Air Bag" },
  { code: "", description: "FREE UP BRAKE SHOES  AXLE" },
  { code: "", description: "Resecure Air Tank" },
  { code: "", description: "Replace Gladhand Holder Bracket" },
  {
    code: "",
    description: "Replace   Gladhand Quick Release Angle 12-236   12236",
  },
  { code: "", description: "Reline with wheel End Inspection" },
  { code: "", description: "Resecure / Refasten Brake Chamber" },
  { code: "", description: "Replace Relay Air Valve RSL115" },
  { code: "", description: "Replace Brake Chamber 3/3" },
  { code: "", description: "Replace Swing Away Gladhand SLN44163  SLN44162" },
  { code: "", description: "Replace  Bracket Mount Gladhand" },
  { code: "", description: "Replace Gladhand Emergency" },
  {
    code: "",
    description:
      "Replace 12-326   12326   Gladhand - Composite, Service / Blue, Shut-Off Valve, Bulkhead Mount, 3/8Ó Port",
  },
  {
    code: "",
    description: "REPLACE AIR  VALVE - FULL FUNCTION (  FF2  KN2861  )",
  },
  { code: "", description: "Replace Clevis Pins + Clevis + Cutter Pin" },
  { code: "", description: "Straighten ABS Bracket" },
  { code: "", description: "Replace ABS Light" },
  { code: "", description: "Resecure / Refasten ABS Harness Wire" },
  { code: "", description: "Replace RSL176B  release air valve push button" },
  { code: "", description: "Replace Shut Off Valve   4414  or 44114" },
  { code: "", description: "Parts : Miscellaneous ( acet,Oxy. WD4 ,Etc.)" },
  { code: "", description: "Repack Removed Hubcap, Repack Nuts axle." },
  { code: "", description: "Replace   Gladhand Seals" },
  { code: "", description: "Replace 1 Air Valve" },
  { code: "", description: "Replace Air Fitting" },
  { code: "", description: "Replace Brake Chamber" },
  { code: "", description: "Replace Brake Hose" },
  { code: "", description: "Replace Brakes Shoes per wheel" },
  { code: "", description: "Replace Bulkhead Fitting" },
  { code: "", description: "Replace Gladhand Bracket Mount 81138B 81138R" },
  { code: "", description: "Replace Slack Adjuster incl Brake Adjustment" },
  { code: "", description: "Replace Wheel Seal" },
  { code: "", description: "Resecure Air Hose" },
  { code: "", description: "Resecure Bulkhead Fitting" },
  { code: "", description: "Replace Air Tank" },
  { code: "", description: "Replace Hubcap" },
  { code: "", description: "Replace Petcock" },
  { code: "", description: "Free Up Slack Adjuster and/or Cam Shaft (each )" },
  { code: "", description: "Replace Brakes Shoes Complete (All Wheels) -" },
  { code: "", description: "Replace Brake Drum (.7)" },
  { code: "", description: "Repair Air Line ( -1)" },
  { code: "", description: "Heat + Free up Clevis and Pins - Frozen" },
  { code: "", description: "Trace and Repair Air System" },
  { code: "", description: "Replace Push Rod Clevis + Pins" },
  { code: "", description: "Replace Plug Fitting" },
  { code: "", description: "Replace Swinger Gladhand" },
  {
    code: "",
    description: "Install hose separator -  Spacer hoses (1-4 per piece )",
  },
  { code: "", description: "Free up Brakes Shoes - Frozen" },
  {
    code: "",
    description:
      "Resecure Push Rod Nut  \n Refasten Brake Chamber Jam Nut",
  },
  { code: "", description: "Replace Bulk Head Fitting" },
  { code: "", description: "Check and Adjust Brakes Front Axle / Rear Axle" },
  { code: "", description: "Reconnect  Marker Lights ( Each )" },
  { code: "", description: "Replace   Gladhand Seals" },
  { code: "", description: "Check and Adjust Brakes" },
  { code: "", description: "Trace and Repair Air Leak" },
  { code: "", description: "Resecure Gladhand + Bulk Head Fitting - Loose" },
  { code: "", description: "Resecure/Refasten  Gladhand - Loose" },
  { code: "", description: "Replace Brakes Shoes and Hardware Kit" },
  { code: "", description: "Replace Brake Chamber LF" },
  { code: "", description: "Replace Brake Chamber LR" },
  { code: "", description: "Replace Brake Chamber RF" },
  { code: "", description: "Replace Brake Chamber RR" },
  {
    code: "",
    description: "Replace Swing Away Gladhand     SLN44163  SLN44162",
  },
  {
    code: "",
    description: "Replace 1 Gladhand Mounting Bracket with Quick release12-236",
  },
  { code: "", description: "Replace 37-1/2 Bracket Mount Gladhand" },
  { code: "", description: "Free up LF Scam Bushings/Slack Adjuster - Frozen" },
  {
    code: "",
    description: "Free up LR  Scam Bushings/Slack Adjuster - Frozen",
  },
  { code: "", description: "Free up RF Scam Bushings/Slack Adjuster - Frozen" },
  { code: "", description: "Free up RR Scam Bushings/Slack Adjuster - Frozen" },
  { code: "", description: "Replace Slack Adjuster Automatic LF" },
  { code: "", description: "Replace Slack Adjuster Automatic LR" },
  { code: "", description: "Replace Slack Adjuster Automatic RF" },
  { code: "", description: "Replace Slack Adjuster Automatic RR" },
  { code: "", description: "Check and Resecure Air System" },
  { code: "", description: "Resecure Air Hoses" },
  { code: "", description: "Resecure Air Hoses with plastics spacers  45137" },
  { code: "", description: "Replace Brake Drum + Brakes Shoes + Hardware Kit" },
  { code: "", description: "Refasten Air Tank" },
  { code: "", description: "Refasten Air Bag Valve Bracket" },
  { code: "", description: "Refasten Air Hoses" },
  { code: "", description: "Refasten/Resecure ABS Harness Wire" },
  { code: "", description: "Refasten Air Fitting" },
  { code: "", description: "Replace Valve Drain Cock  Valve -  Leaking (5)" },
  {
    code: "",
    description: "Replace Air Hoses Support Spring ( Slider Spring )",
  },
  { code: "", description: "Resecure Air Line with Slider Spring" },
  { code: "", description: "Refasten/Straighten  Gladhand Holder Plate" },
  { code: "", description: "Refasten Gladhand Swivel" },
  { code: "", description: "Replace Air Line Fitting" },
  { code: "", description: "Replace Air Brass Fitting" },
  {
    code: "",
    description:
      "Replace 1 Air Valve  VS25223  or VS-25223   HENDRICKSON 3-WAY AUTO RESET VALVE",
  },
  { code: "", description: "Replace 1 Air Valve Release Kit" },
  { code: "", description: "Removed and Reinstall Service Gladhand" },
  { code: "", description: "Replace  Relay Air Valve" },
  {
    code: "",
    description:
      "Replace Swinger Gladhand or Swivel gladhand 9 Degree Service - 12-496   12496",
  },
  { code: "", description: "Replace Brakes Shoes and Hardware Kit" },
  {
    code: "",
    description: "Free up Brakes Shoes and  Slack Adjusters/Lubricate",
  },
  { code: "", description: "Replace Dummy Gladhand" },
  { code: "", description: "Replace Relay Air Valve" },
  {
    code: "",
    description:
      "Replace   Haldex Bracket Kit for Slack Adjuster # 427-1563  or 4271563  ( each)",
  },
  {
    code: "",
    description: "Driving Time  Round Trip \nDate :\nLocation : \nEquipment :",
  },
  { code: "", description: "Check New Lift Gate in Service" },
  {
    code: "",
    description:
      "\r\nComplete Inspection PM/FHWA\r\nCheck  + Air up Tires/ Torque Lug Nuts wheel\r\nLubrication /Grease Axles",
  },
  { code: "", description: "Preventative Maintenance  Lift Gate Inspection" },
  { code: "", description: "Annual Inspection Lift Gate" },
  { code: "", description: "Initial  Lift Gate Inspection" },
  { code: "", description: "Straighten and Weld Right Chain Guide" },
  { code: "", description: "Replace Lift Gate Solenoid - Damage" },
  { code: "", description: "Replace Lift Gate Battery" },
  { code: "", description: "Dead Service Call Road Call Repairs" },
  { code: "", description: "Recharge Battery Lift Gate" },
  { code: "", description: "Replace Retention Ramp Locking Arm Assy" },
  { code: "", description: "Lift Gate Inspection and Lubricate" },
  { code: "", description: "Clean LOF,LOR,ROF,ROR Wheel" },
  { code: "", description: "Check  + Air up Tires/ Torque Lug Nuts wheel" },
  { code: "", description: "Check and Air Up Tires" },
  { code: "", description: "Refill Gear Oil in the Hubcap" },
  { code: "", description: "Installed Electronic Log Book / Elog" },
  { code: "", description: "Remove Graffiti at Nose" },
  { code: "", description: "Tighten Bolt (s) Left , Right ICC Upright (s)" },
  {
    code: "",
    description: "Heat + Straighten ICC Bumper + Install Conspicuity Tape",
  },
  { code: "", description: "Straighten ICC Horizontal Bar" },
  {
    code: "",
    description:
      "Replace  Dock Bumper (Rubber)   \n Bolts + Nuts + Washers",
  },
  { code: "", description: "Replace Left Dock Bumper" },
  { code: "", description: "Replace  Right Dock Bumper" },
  { code: "", description: "Replace ICC Bumper Assy." },
  {
    code: "",
    description:
      "Replace ICC Horizontal DOT Bumper + Paint and Install conspicuity Tape",
  },
  { code: "", description: "Straighten ICC Bumper Upright" },
  { code: "", description: "Heat and Straighten and Weld  ICC Bumper Gusset" },
  { code: "", description: "Heat + Straighten ICC Bumper Upright" },
  {
    code: "",
    description: "Heat + Straight + Weld ICC Bumper Bracket and Reinstall",
  },
  { code: "", description: "Straighten and Weld ICC Bumper" },
  { code: "", description: "Replace Landing Gear Wheel  Metal Caster" },
  { code: "", description: "Replace Eye Hook Latch Kit \n #4X137" },
  {
    code: "",
    description:
      "Replace Handle Assembly - With Roll Pin - 8” long (for use on 6, 7 and 8 series Jacks)",
  },
  { code: "", description: "Replace  - Eye Hook Latch kit  #  4X137" },
  {
    code: "",
    description: "Pull Handle Kit For Fifth Wheel. Left Release - KIT-PUL-  6L",
  },
  { code: "", description: " Replace 7 way  Plug Conductor 15-73" },
  { code: "", description: "Replace Pull Button Valve RSL176B  or 176B" },
  { code: "", description: "Check Lights" },
  { code: "", description: "REPLACE TAIL LIGHT" },
  { code: "", description: "Replace Turn Indicator Lamp" },
  { code: "", description: "Replace Pig Tail - Plug ( 3 Way )" },
  { code: "", description: "Replace Reflectors round" },
  {
    code: "",
    description: 'Marker Light 2" Round Red Non Flange 321Y  or  321R',
  },
  {
    code: "",
    description: 'Replace  Marker Light LED 2" with Flange 351Y  or  351R',
  },
  { code: "", description: "Reconnect Market Light" },
  { code: "", description: "REPLACE L/ PLATE LIGHT" },
  { code: "", description: "Replace License Plate Mount Plastic" },
  {
    code: "",
    description:
      "Replace License Plate Light and Plastic Mount # 1511 ,  152c3",
  },
  { code: "", description: "Replace Electrical Plug - 7 Way" },
  { code: "", description: "RESECURE 7 WAY" },
  { code: "", description: "RESECURE LOOSE WIRING" },
  { code: "", description: "REPLACE BOLSTER HARNESS LEFT" },
  { code: "", description: "Labor : REPLACE BOLSTER HARNESS RIGHT" },
  { code: "", description: "REPLACE LIGHT BRACKET" },
  { code: "", description: "REPLACE ABS LIGHT" },
  { code: "", description: "Replace Harness wire Cable (7 way)" },
  { code: "", description: "Replace Harness wire Cable and butt connecters" },
  {
    code: "",
    description:
      "Replace complete Harness wire and Rewire - Rear Bolster  - 53' FT",
  },
  { code: "", description: "Replace 7 Way (Small)" },
  { code: "", description: "TRACE + REPAIR ELECTRICAL PROBLEM." },
  { code: "", description: "REPLACE BULBS" },
  { code: "", description: "Repair Wire Broken" },
  { code: "", description: "Install Conspicuity Tape" },
  { code: "", description: "Replace Stop Light" },
  { code: "", description: "Inspection Trailer Lights" },
  {
    code: "",
    description: "Remove and Reinstall Stop Light Safety Cover Plate",
  },
  { code: "", description: "Straight Signal Light Bracket" },
  { code: "", description: "Replace Stop Light  with Flange" },
  {
    code: "",
    description: 'Replace Marker Light Oval 4"  and Plastic Base   ',
  },
  { code: "", description: "Replace License Plate Light and Plastic Base" },
  { code: "", description: "Replace Marker Light  (Non Flange )" },
  { code: "", description: "Replace Marker Light with Flange" },
  { code: "", description: "Replace Marker Light  Rectangle LED  Front  Top" },
  { code: "", description: "Replace Marker Light Rectangle LED  Rear Top" },
  { code: "", description: "Replace Marker Light Plug" },
  { code: "", description: "Replace Marker Light Rectangle  Regular" },
  {
    code: "",
    description:
      "Replace Marker Light Rectangle  Regular  and  Plastic Base -Front  Top",
  },
  {
    code: "",
    description:
      "Replace Marker Light Rectangle  Regular and Plastic Base   -Rear Top",
  },
  { code: "", description: "Replace  Marker Light Rectangular LED Front  Top" },
  { code: "", description: "Replace  Marker Light Rectangular LED Rear Top" },
  { code: "", description: "Replace pig tail plug  2 way" },
  {
    code: "",
    description: "Replace Marker Light Oval 4'  and Plastic Base   Front Top",
  },
  {
    code: "",
    description:
      "Replace Marker Light Oval 4' + Plastic Base  Rear Top  and Screws",
  },
  { code: "", description: "Replace Stop Light Grommet" },
  { code: "", description: "Replace 7 Way Large" },
  {
    code: "",
    description: "Replace Marker Light  Rectangular regular Front Top",
  },
  {
    code: "",
    description: "Replace Marker Light  Rectangular regular Rear Top",
  },
  { code: "", description: "Replace Stop Light Kit Square" },
  { code: "", description: "Replace 7 Way Aluminum Mount" },
  { code: "", description: "Replace Stop Light Regular (Non Flange )" },
  { code: "", description: "Trace and Repair Electrical Problem" },
  { code: "", description: "Replace pigtail - plug (3 way)" },
  {
    code: "",
    description:
      'Replace Turn Signal Light 6"  Oval Regular \n6215Y3 Marker Light Oval 6"  Turn Signal Light',
  },
  { code: "", description: "Replace 7 Way small" },
  { code: "", description: "Replace Turn Signal Light 6' Grommet" },
  { code: "", description: "Replace Pigtail plug - 2 way" },
  { code: "", description: "Replace Power Electrical Cord" },
  {
    code: "",
    description: "Resecure  Power Electrical Cord with Steel Wire and Lock",
  },
  { code: "", description: "Replace Marker Light Round 2 1/2 Rear Bottom" },
  { code: "", description: "Replace Round Marker Light  -Front  Top 2 1/2" },
  { code: "", description: "Replace Round Marker Light  -Rear Top 2 1/2" },
  { code: "", description: "Resecure / Refasten Harness wire with  zip tie" },
  { code: "", description: "Resecure  / Refasten 7 Way" },
  { code: "", description: "Replace Marker Light  Rectangular regular" },
  { code: "", description: "Replace 7 Way lid kit" },
  { code: "", description: "Reinstall/ Refasten Marker Light Top" },
  { code: "", description: "Replace 7 way and Aluminum Nose box Mount" },
  { code: "", description: "Replace Junction Box" },
  { code: "", description: "Replace Led Marker Light with Flange 2'" },
  { code: "", description: "Replace Market Light Grommet" },
  {
    code: "",
    description: "Replace Pig Tail Plug LED For Rectangle Marker Light",
  },
  { code: "", description: "Replace Pigtail plug - (2 Ways)" },
  { code: "", description: 'Replace Signal Light with Flange Oval 6" ' },
  { code: "", description: 'Replace Stop Light 4" with Flange.' },
  { code: "", description: "Replace Stop Light Grommet" },
  { code: "", description: "Replace Marker Light  Grommet 2'" },
  { code: "", description: "Replace 7 way Receptacle" },
  { code: "", description: "Replace 7 way" },
  { code: "", description: "Replace Pigtail plug 2 way" },
  { code: "", description: "Replace Pigtail Plug 3 way" },
  {
    code: "",
    description:
      "Trace and Repair ABS Problem  \n Troubleshoot ABS System",
  },
  { code: "", description: "Replace License Plate" },
  { code: "", description: "Reconnect Stop Lights" },
  { code: "", description: "Resecure Electrical Wires" },
  { code: "", description: "Trace and Repair Electrical problem" },
  { code: "", description: "Replace Stop Light" },
  { code: "", description: "Replace Stop Light Grommet" },
  { code: "", description: "Replace Marker Light non flange" },
  { code: "", description: "Replace LED Marker Light" },
  { code: "", description: "Replace Tail Light" },
  { code: "", description: "Trace + Repair  Electrical Problem" },
  { code: "", description: "Check Lights" },
  { code: "", description: "Resecure 7 Way Connector  wires" },
  { code: "", description: "Replace Pig Tail Plug - 3 Way" },
  { code: "", description: "Replace LED Pigtail Plug - 3 Way\r" },
  { code: "", description: "Replace Pig Tail Plug LED #94862" },
  { code: "", description: "Replace Pigtail Plug" },
  { code: "", description: "Inspection Trailer Lights" },
  { code: "", description: "Replace Stop Light Grommet" },
  { code: "", description: "Replace Marker Light" },
  {
    code: "",
    description: "Replace Marker Light and Plastic Base   ( per Unit)",
  },
  {
    code: "",
    description: "Replace Marker Light Front Top and Plastic Base  ( per Unit)",
  },
  {
    code: "",
    description:
      "Replace Marker Light Rear  Top and  Plastic Base  ( per Unit)",
  },
  { code: "", description: "Replace License Plate Light" },
  { code: "", description: "Replace License Plate Light and Plastic Mount" },
  { code: "", description: "Straight License Plate Bracket" },
  { code: "", description: "Replace Marker Light Base" },
  {
    code: "",
    description: "Replace Marker Light Rectangle  Regular  - Front Top",
  },
  {
    code: "",
    description: "Replace Marker Light Rectangle  Regular  -Rear Bottom",
  },
  {
    code: "",
    description: "Replace Marker Light Rectangle  Regular  -Rear Top",
  },
  { code: "", description: "Replace LED  Stop Light Non Flange" },
  { code: "", description: "Resecure/ Refasten 7 Way" },
  { code: "", description: "Replace 7 Way Large" },
  { code: "", description: "Replace 7 Way and  Mount" },
  { code: "", description: "Replace Marker Light Bulb" },
  { code: "", description: "Replace ABS Light" },
  { code: "", description: "Replace Marker Light Gromet" },
  {
    code: "",
    description: "Replace LED Marker Lights 3/4'  Front Top ( each)",
  },
  { code: "", description: "Replace LED Marker Lights 3/4'  Rear Top ( each)" },
  {
    code: "",
    description: "Replace LED Marker Lights 3/4'  Rear Bottom ( each)",
  },
  {
    code: "",
    description:
      "Replace LED Marker Lights Rectangle and pigtail plug  -Top ( Each)",
  },
  { code: "", description: 'Replace Signal/Marker Light with Flange Oval 6" ' },
  { code: "", description: "Replace LED Marker Light Rectangular Front Top" },
  {
    code: "",
    description: "Replace LED Marker Light  Rectangular-Bottom Rear",
  },
  { code: "", description: "Replace LED Marker Light Rectangular Rear Top" },
  { code: "", description: "Replace LED Marker Light 3/4 Left Rear - Bottom" },
  { code: "", description: "Replace LED Marker Light 3/4 Right Rear - Bottom" },
  { code: "", description: "Reinstall/Refasten Marker Light Top" },
  {
    code: "",
    description:
      'Replace Marker Light Oval 4" Regular with plastic Base Front  Top  ',
  },
  {
    code: "",
    description:
      'Replace Marker Light Oval 4" Regular with plastic Base Rear Top ',
  },
  { code: "", description: "Replace 7 Way - Small" },
  { code: "", description: "Refasten Marker Light Rear Top" },
  { code: "", description: "Replace Junction Box" },
  { code: "", description: "Refasten Left  Mid Turn Light Bracket" },
  { code: "", description: "Refasten Right Mid Turn Light Bracket" },
  { code: "", description: "Replace Base Bottom Light (s) Marker  Regular" },
  { code: "", description: "Replace Base Top Light (s) Marker  Regular" },
  { code: "", description: "Straighten Left Mid Turn Light Bracket" },
  { code: "", description: "Straighten Right Mid Turn Light Bracket" },
  { code: "", description: "Rewire Lights" },
  { code: "", description: "Troubleshoot Lighting System Fault" },
  { code: "", description: "Replace Stop Light Regular with Flange" },
  { code: "", description: "Replace LED Stop Light with Flange" },
  {
    code: "",
    description: 'Replace Signal Marker Light Oval 6" with Flange  ',
  },
  { code: "", description: "Straighten Signal Turn Light Bracket" },
  { code: "", description: "Replace LED pigtail plug" },
  { code: "", description: "Replace 1728 Marker Light Plastic Bracket" },
  { code: "", description: "Replace Light House" },
  {
    code: "",
    description:
      "Replace Marker Light LED with Flange \n Use 3 Rivet / Screw",
  },
  { code: "", description: 'Replace Signal Light Mounting Bracket 6" ' },
  {
    code: "",
    description:
      "Replace Adapter Plate - Adapter, powder-coated, 1 ga. steel 15-77",
  },
  { code: "", description: 'Stop Light Oval 6" regular  - Non Flange  ' },
  { code: "", description: "Removed + Reinstalled Stop Light Cover Plate" },
  { code: "", description: "Reenforce Cross Member  with Steel Plate" },
  { code: "", description: "Straighten Door Frame" },
  { code: "", description: "Weld Door Frame Left Side and Right Side" },
  { code: "", description: "Weld Door Frame Left Side" },
  { code: "", description: "Weld Door Frame Right Side" },
  { code: "", description: "Replace Trailer Cross Member" },
  { code: "", description: "Replace Slider Safety Pin" },
  { code: "", description: "Straighten Crossmembers - Over Tandem" },
  {
    code: "",
    description: "Straighten + Weld  Swing Door Hinge Bracket Left Side  -",
  },
  { code: "", description: "Heat + Straighten Door Frame" },
  {
    code: "",
    description: "Heat + Straighten + Weld  Crossmember (s) - Over Legs",
  },
  { code: "", description: "Removed   GPS Equipment  of the chassis" },
  { code: "", description: "Troubleshoot Trlr Tracking Sys." },
  { code: "", description: "Replace Trlr Tracking Sys- Basic" },
  { code: "", description: "Replace Trlr Tracking Antenna" },
  { code: "", description: "Replace Tracking System Battery" },
  { code: "", description: "Remove Cust Owned Tracking  Unit \r" },
  { code: "", description: "RESECURE ID PLATE" },
  { code: "", description: "REPLACE LIC. PLATE" },
  { code: "", description: "Paint  Stencil Prefix Numbers/Chassi Number" },
  {
    code: "",
    description:
      "Paint Front Bolster Red and \r\n Paint Out BACP/Shipper and SSA                           Stencil",
  },
  { code: "", description: "Complete FMCSA (annual)" },
  {
    code: "",
    description:
      "Complete FMCSA (annual) and BIT Inspection (9 Days).  \n Adjust Brakes \n Lube and Grease Axles and Landing Legs",
  },
  { code: "", description: "Complete BIT Inspection 90 Days" },
  { code: "", description: "Roadability Inspection" },
  { code: "", description: "Replace Document   Holder" },
  { code: "", description: "Replace Federal Sticker / FMCSA Decal" },
  {
    code: "",
    description: "Trailer # \nRoadability Inspection  and Lubricate Axles",
  },
  { code: "", description: "Trailer #\n Complete Trailer Inspection PM" },
  {
    code: "",
    description:
      "Roadability Inspection \n Check  and Air up Tires \n Check Air System - Brakes \n Check Electrical System",
  },
  { code: "", description: "Dry Run  - Service Cancelled or not  Completed." },
  {
    code: "",
    description:
      "Equipment # \nDolly PM Service  \nAdjust Brakes \nLubricate Axles and 5th Wheel",
  },
  {
    code: "",
    description: "BIT INSPECTION TRUCK\r\n\r\nTruck # \r\nDriver Name :",
  },
  { code: "", description: "Replace Timing Bar  (.5)" },
  { code: "", description: "Replace 1 Set Landing Legs" },
  { code: "", description: "STRAIGHT  LEG - Bent" },
  { code: "", description: "STRAIGHT BOTH LEGS" },
  { code: "", description: "REPLACE DUST COVER" },
  { code: "", description: "REPLACE SHORT BRACE ( Bent / Broken / Missing )" },
  { code: "", description: "REPLACE CROSS BRACE - Bent / Broken" },
  { code: "", description: "REPLACE CRANK HANDLE" },
  { code: "", description: "Replace Crank Shaft Jost" },
  { code: "", description: "REPLACE CRANK SHAFT HOLLAND" },
  { code: "", description: "STRAIGHT CRANK SHAFT" },
  { code: "", description: "Replace Cross Over Shaft" },
  { code: "", description: "TIME LEGS" },
  { code: "", description: "WELD LEG BOX" },
  { code: "", description: "REBUILT GEAR BOX" },
  { code: "", description: "REPLACE GEAR BOX COVER" },
  { code: "", description: "REPLACE GEAR BUSHING" },
  { code: "", description: "REPLACE SAND SHOE" },
  { code: "", description: "REPLACE AXLE HOUSING" },
  { code: "", description: "STRAIGHT AND WELD SAND SHOW AND AXLE" },
  { code: "", description: "RETIGHT LEG BOLTS" },
  { code: "", description: "RESECURE LEG" },
  {
    code: "",
    description: "Labor Remove, Straighten and Reinstall one small cross brake",
  },
  { code: "", description: "Replace ear leg broken" },
  { code: "", description: "Heat + Str Ear Legs - Bent" },
  { code: "", description: "Reweld Landing Leg Mounting Bracket" },
  { code: "", description: "Replace Mounting Bracket  Leg -" },
  {
    code: "",
    description:
      "Replace 1 Set Austin Leg - Damage +\r\n Replace 6 Ear Legs \r\n Replace 8 Bolts and Nuts 5/8",
  },
  { code: "", description: "Resecure/Refasten Landing Leg" },
  { code: "", description: "Replace Crank Handle Retainer" },
  {
    code: "",
    description:
      "Replace Set Landing Legs  - Gear side and Non Gear Side  .\n Replace Bolts and Nuts \n Replace Ear Braces \n Paint",
  },
  { code: "", description: "WELD 1 LEG" },
  { code: "", description: "STRAIGHT AND RESECURE GEAR BOX" },
  { code: "", description: "REPLACE ROLL PIN" },
  { code: "", description: "Replace Sand Shoes ( High  / Short  ) and Axle" },
  {
    code: "",
    description:
      "WELD BRACE EAR - LEG  + \r\n REPLACE 2 BOLTS + NUTS 5/8",
  },
  { code: "", description: "RESECURE BRACES" },
  { code: "", description: "Weld Ear Leg" },
  { code: "", description: "Replace Leg Top Cover" },
  { code: "", description: "Heat + Straighten 5th Wheel Handle" },
  { code: "", description: "Repair Crank Handle" },
  {
    code: "",
    description:
      "Replace 1 Set  Landing Leg  \n Replace Ear Braces \n Replace Bolts and Nuts 5/8\n Paint",
  },
  { code: "", description: "Replace Ear Brace" },
  {
    code: "",
    description: "Replace Crank Handle Bolt + Nut + Washer - Broken/Missing",
  },
  { code: "", description: "Replace Sand Shoes Axles &/OR Wheels" },
  { code: "", description: "Replace San shoes Housing" },
  { code: "", description: "Weld Mounting Bracket" },
  { code: "", description: "Resecure - Refasten Leg  Braces" },
  { code: "", description: "Replace Crank Handle" },
  {
    code: "",
    description: "Straight/Weld  Landing Legs/Braces/Gear Box/Skirts .",
  },
  { code: "", description: "Replace Crank Shaft" },
  { code: "", description: "Retime Landing Legs" },
  { code: "", description: "Replace Ear Leg" },
  {
    code: "",
    description: "Replace Landing Legs  - Gear Side and Non Gear Side .",
  },
  { code: "", description: "Replace 1 Landing Leg  Jost" },
  { code: "", description: "Refasten/Resecure  Cross Brace Channel - Loose" },
  { code: "", description: "Straighten Sand Shoes" },
  { code: "", description: "Lubricate Landing Gear" },
  { code: "", description: "Replace Crank Handle" },
  { code: "", description: "Straighten Landing Gear K-Brace" },
  { code: "", description: "Straighten Non Gear Leg" },
  {
    code: "",
    description: "Replace  Set Landing Leg (Gear Side and Non Gear Side",
  },
  { code: "", description: "Straighten Left, Right Landing Gear - Wing Brace" },
  { code: "", description: "Straighten Cross Brace Small" },
  { code: "", description: "Straighten Cross Brace Large (Channel)   -" },
  { code: "", description: "Straighten Landing Gear  - Cushion Foot" },
  { code: "", description: "Weld Landing Gear-Wing Brace" },
  { code: "", description: "Straighten Landing Gear - Wing Brace" },
  { code: "", description: "Replace Crank Handle Holder / Retainer" },
  { code: "", description: "Weld Ear Braces  / K  Brackets" },
  { code: "", description: "Straighten and Weld Landing Legs" },
  { code: "", description: "Chisel Landing Leg Bands" },
  {
    code: "",
    description:
      "Replace Sand Shoes  Axle  Housing  \n Cut off with Torch and Weld new Axle housing",
  },
  { code: "", description: "Straighten Crank Handle Retainer" },
  { code: "", description: "Fabricate Landing Legs Brackets" },
  {
    code: "",
    description: "Replace Set Landing Legs ( Gear side and Non Gear Side ) .",
  },
  {
    code: "",
    description:
      "Recycle oil by Gallon.\n (Charge for collection, transportation, and processing of used motor oil)",
  },
  {
    code: "",
    description:
      "Pick up  the engine filter and motor oil in the shop and after recycle the filter and oil in the workshop recycling container",
  },
  { code: "", description: "Replace  Engine Oil  \n Replace Oil Filter" },
  {
    code: "",
    description:
      "Replace Conspicuity Tape \n Clean Area to Install Conspicuity Tape",
  },
  { code: "", description: "Installed License Plate" },
  { code: "", description: "Replace Registration Holder / Document Holder" },
  { code: "", description: "Install Registration" },
  { code: "", description: "Replaced Placard Holder" },
  { code: "", description: "Straighten License Plate Bracket" },
  { code: "", description: "Snow Chains Inspection" },
  {
    code: "",
    description: "Replaced Mud Flap Bracket  with Steel Angle 1/4X2' and Paint",
  },
  { code: "", description: "Fabricate  Mudflap Bracket  with Angle support ." },
  { code: "", description: "STRAIGHT MUDFLA P BRACKET" },
  { code: "", description: "Resecure Mudflaps with bolts ,nuts and washers" },
  { code: "", description: "Replace Mud Flap  Bracket" },
  { code: "", description: "Replace Mudflap  24 X 24" },
  { code: "", description: "Replace B25P Steel Bar Mudflap Bracket" },
  { code: "", description: "Replace \tMud Flap Hanger Mounting Bracket  # K7" },
  { code: "", description: "Straighten Mudflap Bracket" },
  { code: "", description: "Heat + Straighten and Weld Mudflap Bracket" },
  { code: "", description: "Resecure Mudflap" },
  { code: "", description: "Replace Mudflap Bracket" },
  {
    code: "",
    description:
      "Trace + Repair Electrical Short Reefer  container Harness Wire",
  },
  { code: "", description: "Replace Reefer  power plug Male" },
  { code: "", description: "Replace Roller Door Pull Strap" },
  { code: "", description: "Refasten  /  Resecure Roller Door Hinge" },
  {
    code: "",
    description: "Replace Roller Door Wheel and Roller Door Hinge End",
  },
  { code: "", description: "Lubricate Roller Door" },
  {
    code: "",
    description: "Weld  / Refasten Horizontal Roller Door Rail  Left Side",
  },
  {
    code: "",
    description: "Weld  / Refasten Horizontal Roller Door Rail  Right  Side",
  },
  { code: "", description: "Refasten Roller Door Hinge / Wheel" },
  { code: "", description: "Straighten Roller Door Panels" },
  {
    code: "",
    description: "Refasten / Resecure  Roller Door Rail   ( per side )",
  },
  { code: "", description: "Replace Complete Roller Door" },
  {
    code: "",
    description:
      "Replace Roller Door Lock  Keeper Assembly 25152  / 25-152      \n + 3 Elevator Bolts and Nuts",
  },
  { code: "", description: "Replace Lower Rail of Roller Door" },
  { code: "", description: "Replace  Roll up door spring adjustment Dual" },
  { code: "", description: "Replace Center Hinge" },
  { code: "", description: "Replace Roller Door Wheel" },
  {
    code: "",
    description: "Remove + Straighten + Reinstall Bottom  Roller Door Panel",
  },
  { code: "", description: "Lubricate Roller Door" },
  { code: "", description: "Replace Bottom Roller Door Panel" },
  { code: "", description: "Replace Intermediate Panel" },
  { code: "", description: "Resecure Roller Door Hinge End." },
  { code: "", description: "Reinstall Roller" },
  { code: "", description: "Adjust Counter Balance Assemblies" },
  {
    code: "",
    description: "Replace Roller Door Wheel and Roller Door Hinge End",
  },
  {
    code: "",
    description:
      "Replace Roller Door Wheel Todco + Roller Door Hinge End Todco + Bolts and Nuts",
  },
  { code: "", description: "Straighten Roller Door Rail by Rail" },
  { code: "", description: "Replace Roll Door Bottom Panel" },
  { code: "", description: "Replace Roller Door Wheel" },
  { code: "", description: "Replace  Roller Door End Hinge + Wheel" },
  { code: "", description: "Replace Pull Strap" },
  { code: "", description: "Refasten Roller Hinge" },
  {
    code: "",
    description:
      "Replace Roller Door  Hinge Top with Bracket Assembly Part # 56125-12  or 25-12   2512",
  },
  { code: "", description: "Replace Center  Roller Door Hinge" },
  { code: "", description: "Replace Roller Door Hinge End" },
  { code: "", description: "Adjust Operator" },
  {
    code: "",
    description: "Replace  Roller Door Lock Assembly and Roller Door Keeper",
  },
  { code: "", description: "Adjust Roller Door Cable" },
  { code: "", description: "Replace   Roller Door Cable ( each)" },
  { code: "", description: "Reinstall Roller Door Wheel" },
  { code: "", description: "Replace Roller Door Cable Bracket  TOD 6124" },
  { code: "", description: "Replace Roller Door Reenforce Hinge End" },
  {
    code: "",
    description:
      "Replace Roller Door Reenforce Hinge End  and  Roller Door Wheels",
  },
  { code: "", description: "Replace Counter Balance Spring Adjuster" },
  {
    code: "",
    description:
      "Replace Roller Door Lift Handle  whi1715  \n Replace Bolts and Nuts",
  },
  { code: "", description: "Installed Conspicuity Tape" },
  { code: "", description: "Installed  Equipment numbers" },
  { code: "", description: "Install McKinney WWW Decal Rear Door" },
  { code: "", description: "Install Skybitz Unit" },
  {
    code: "",
    description: "REPLACE  TORQUE ARM AND ALIGNMENT ( Solid or Adjustable)",
  },
  { code: "", description: "RETIGHTEN / RESECURE TORQUE ARM- Loose" },
  { code: "", description: "ALIGN AXLES" },
  {
    code: "",
    description:
      "Replace 1 Suspension Spring               Bracket - Bottom Plate- Cracked \r\n Replace 1 Set  U-Bolts + Bolts and                     Nuts",
  },
  { code: "", description: "Align Axles" },
  {
    code: "",
    description:
      "Replace Hutch Equalizer  with  Rocker Bolt Kit  \n Heat + Cut with Torch  Equalizer bolt",
  },
  {
    code: "",
    description:
      "Replace U-Bolts Kit \r\n Replace Suspension  Bracket\r\n Replace Torque Arm",
  },
  {
    code: "",
    description:
      "Removed + Install New Spring Hanger \r\n and Equalizer - Damage \r\n Replace Hardware Kit Equalizer\r\n (Removed + Reinstall Torque Arm)",
  },
  { code: "", description: "Replace Spring Hanger" },
  { code: "", description: "Resecure U-Bolts / Torque All U-Bolts" },
  {
    code: "",
    description:
      "Replace Spring Suspension  \n Replace U-Bolts \n Replace Sleeve Tube \n Replace Sleeve Bolt and Nut",
  },
  { code: "", description: "Replace Sleeve Bolt Suspension" },
  {
    code: "",
    description: "Replace U-Bolts (Pair .7)\n Replace Nuts",
  },
  { code: "", description: "Free up and  Lubricate Slider Pins" },
  { code: "", description: "Retorque U-Bolts axle" },
  {
    code: "",
    description:
      "Complete In Service New Unit  \r\n Torque Suspension\r\n Torque LF,LR,RF,RR Wheel Nuts - All \r\n Positions\r\n Torque LR,LR,RF,RR Hubcaps Bolts-\r\n All Positions \r\n Check Tire Pressure",
  },
  { code: "", description: "Reinstall Bulk Head" },
  { code: "", description: "Replace Dust Plug(s) Brake Chamber" },
  { code: "", description: "Replace Absorber shocks" },
  { code: "", description: "Straighten Bulk Head" },
  { code: "", description: "Repair Air Bag Valve" },
  { code: "", description: "Reseat bell/  Free up Air Bag" },
  { code: "", description: "Adjust Valve - Leveling" },
  { code: "", description: "Retorque Suspension / Wheels" },
  { code: "", description: "Retorque  Landing Leg Fasteners" },
  { code: "", description: "Check Axles and Subframe" },
  {
    code: "",
    description:
      "Replace Front Spring Hanger \n Replace Torque Arm Adjustable \n Align the Axle",
  },
  {
    code: "",
    description:
      "Replace Air Hose 6ft + 1 Gladhand Universal + 2 Spring Guard Fitting  Emergency",
  },
  {
    code: "",
    description:
      "Replace  Air Hose 4ft + 1 Gladhand Universal + 2 Spring Guard Fitting  ,Service",
  },
  {
    code: "",
    description:
      "Replace Trailer Connector Cord & Hose Separators / Holders  81138  81-138",
  },
  {
    code: "",
    description:
      "Replace 15 ft Air Hose + 2 Air Fitting + 1 Gladhand and Resecure  \n (Truck Air System )",
  },
  {
    code: "",
    description: "Replace  Clevis Pins + Clevis + Cutter pins # R8119",
  },
  {
    code: "",
    description:
      "Replace  Spring Pad Wear .\n Jack Up , Remove the Old Pad  with Torch + Grinder and Weld",
  },
  { code: "", description: "Replace Leveling  Control Valve" },
  { code: "", description: "Replace  air spring actuator assembly S25593" },
  { code: "", description: "Patch  X  Left Front Radius Panel" },
  { code: "", description: "Weld  /  Resecure Threshold Plate" },
  { code: "", description: " Refasten Threshold Plate" },
  { code: "", description: "Patch 1ft X 1 ft  Left  Side Wall Panel" },
  { code: "", description: "Patch 1ft X 1 ft  Right Side Wall Panel" },
  { code: "", description: "Patch 1ft X  ft Left   Side Wall Panel" },
  { code: "", description: "Patch 1ft X  ft Right  Side Wall Panel" },
  { code: "", description: "Straighten Cross Member" },
  { code: "", description: "Weld Stop Light Housing Left  Side" },
  { code: "", description: "Weld Stop Light Housing Right Side" },
  { code: "", description: "Weld ICC Bumper Horizontal" },
  { code: "", description: "Resecure ICC Bumper" },
  { code: "", description: "Lubrication Slider" },
  { code: "", description: "Straighten and Weld Main Rear Frame" },
  { code: "", description: "Weld ICC Bumper Gusset" },
  { code: "", description: "Weld Cross members" },
  { code: "", description: "Straighten & Refasten Left Inner Radius Panel" },
  { code: "", description: "Straighten & Refasten Right  Inner Radius Panel" },
  { code: "", description: "Straighten & Refasten Left Radius Panel\r" },
  { code: "", description: "Straighten & Refasten Right Radius Panel\r" },
  { code: "", description: "Patch 1 ft x 1 ft Left  Radius Panel" },
  { code: "", description: "Patch 1 ft x 1 ft Right Radius Panel" },
  { code: "", description: "Replace 1 Left Radius Panel Protector" },
  { code: "", description: "Patch  X  Left Front Radius Panel" },
  { code: "", description: "Patch  X  Right  Radius Panel" },
  { code: "", description: "Reseal Left Radius Panel" },
  { code: "", description: "Section  Left Radius Panel" },
  { code: "", description: "Replace Radius Panel Complete" },
  { code: "", description: "Replace Corner Cap" },
  { code: "", description: "Reseal Left Corner Cap" },
  { code: "", description: "Section 2 ft Left  Radius Panel" },
  { code: "", description: "Section 2 ft Right Radius Panel" },
  { code: "", description: "Patch  ft X  ft Left Radius Panel" },
  { code: "", description: "Patch  ft X  ft Right  Radius Panel" },
  { code: "", description: "Section 3 ft Left Radius Panel" },
  { code: "", description: "Section 3 ft Right Radius Panel" },
  { code: "", description: "Section 2' X 1' Radius Panel" },
  { code: "", description: "Straight and Weld Front Bolster" },
  { code: "", description: "Replace Slider Handle" },
  { code: "", description: "Straighten Roof Bow" },
  { code: "", description: "Patch 1ft X 1 ft  Left  Side Wall Panel" },
  { code: "", description: "Patch 1ft X 1 ft Right  Side Wall Panel" },
  { code: "", description: "Section & Reinforce 12 ft  Left Bottom Rail" },
  { code: "", description: "Patch 1ft X  ft Left   Side Wall Panel" },
  { code: "", description: "Patch 1ft X  ft Right  Side Wall Panel" },
  { code: "", description: "Straighten & Reinforce Left Bottom Rail" },
  { code: "", description: "Straighten & Weld Header" },
  { code: "", description: "Patch  ft X  ft Left Side Panel" },
  { code: "", description: "Patch  ft X  ft  Right Side Panel" },
  { code: "", description: "Replace Door Seal - Complete" },
  { code: "", description: "Patch 1 ft X  ft Left Radius Panel" },
  { code: "", description: "Patch 1 ft X  ft Right  Radius Panel" },
  { code: "", description: "Patch 1 ft X 1 ft Front Wall Panel" },
  { code: "", description: "Replace Left Front Corner  Cap" },
  { code: "", description: "Replace Left Side Door Seal" },
  { code: "", description: "Replace Right side Door Seal" },
  { code: "", description: "Straighten Door  Lock Rod - Bent" },
  { code: "", description: "Straighten  Swing Door Hinge Butt  / Bracket" },
  { code: "", description: "Lubricate Rollers" },
  { code: "", description: "Straighten Left  Door Handle Keeper" },
  { code: "", description: "Straighten Right Door Handle Keeper" },
  { code: "", description: "Refasten Right Hold Back (Swing Door)" },
  { code: "", description: "Straighten Door Panel" },
  { code: "", description: "Replace Complete Door Seal" },
  { code: "", description: "Straighten Roll Door Bottom Panel" },
  { code: "", description: "Replace Top Right Door seal" },
  { code: "", description: "Buff - Bottom Rail ( per feet)" },
  { code: "", description: "Replace 1 Bottom Dorr Lock Bracket and Bushing" },
  { code: "", description: "Replace Left Lock Rod" },
  { code: "", description: "Replace Right  Lock Rod" },
  { code: "", description: "Resecure Swing Door Hinge" },
  { code: "", description: "Replace Left Radius Panel (Patch)" },
  { code: "", description: "Straight Left Door Panel" },
  { code: "", description: "Straight  and Weld Hinge Bracket (Butt) -" },
  { code: "", description: "Replace Safety Pin" },
  { code: "", description: "Patch  ft X  ft  Right Door Panel" },
  { code: "", description: "Refasten Threshold Plate" },
  { code: "", description: "Replace Lock Rod Bushing" },
  { code: "", description: "Seal Cut Right Side Panel" },
  { code: "", description: "Replace Swing Door Hinge" },
  { code: "", description: "Rehang Left  Swing Door Panel" },
  { code: "", description: "Rehang Right Swing Door Panel" },
  {
    code: "",
    description:
      "Replace  Door Panel and Install  Hardware /Hinges/Door seals / Conspicuity Tape / Bolts and Nuts",
  },
  { code: "", description: "Straighten & Reinforce Left Top Rail Flange" },
  { code: "", description: "Straighten & Reinforce Left Top Rail Flange" },
  { code: "", description: "Refasten Door Seal and Fitting" },
  { code: "", description: "Refasten Left Door Seal" },
  { code: "", description: "Refasten Right Door Seal" },
  { code: "", description: "Replace  Left/ Side  Door Seal Inside/Outside" },
  { code: "", description: "Replace  Side Right Door Seal  Inside/Outside" },
  { code: "", description: "Replace - Bottom Left Door Seal" },
  { code: "", description: "Replace - Bottom Right Door Seal" },
  { code: "", description: "Straighten Door Lock Rod  -  Left  Side" },
  { code: "", description: "Straighten Door  Lock Rod  -  Right Side" },
  { code: "", description: "Straighten Swing Door Hinge Bracket Left Side  -" },
  { code: "", description: "Straighten Swing  Door Hinge Bracket Right Side" },
  { code: "", description: "Straighten Left Swing Door Hinge" },
  { code: "", description: "Straighten & Refasten Scuff-Steel" },
  {
    code: "",
    description: "Removed +  Straighten + Reinstall    Roller Door End Hinge",
  },
  {
    code: "",
    description: "Straight and Refasten  Left Scuff- Aluminum  ( ft)",
  },
  { code: "", description: "Straighten Right Door Panel" },
  { code: "", description: "Straighten Left Side Post - Interior" },
  { code: "", description: "Straighten Left Door Handle" },
  { code: "", description: "Straighten Right Door Handle" },
  { code: "", description: "Refasten Linning (s) - Plywood" },
  { code: "", description: "Replace Section Left Scuff-Aluminum ( each ft)" },
  { code: "", description: "Replace Section Right Scuff-Aluminum ( each ft)" },
  { code: "", description: "Remove Retaining Holder ( for unit)" },
  { code: "", description: "Remove Left  Temp Load Restraint Holder" },
  { code: "", description: "Remove Right Temp Load Restraint Holder" },
  { code: "", description: "Refasten Scuff-Hard Wood" },
  { code: "", description: "Section Left Scuff-Aluminum ft' ( by ft )" },
  { code: "", description: "Section ft Right Side Panel Closure Strip" },
  { code: "", description: "Seal Cut  Left  Side Door  Panel -" },
  { code: "", description: "Seal Cut  Right Side Door  Panel -" },
  { code: "", description: "Removed +Straighten + Reinstall Threshold" },
  { code: "", description: "Refasten Threshold Plate" },
  { code: "", description: "Replace Door Plate Anti-Theft ST" },
  { code: "", description: "Straighten Anti Theft Door Plate" },
  { code: "", description: "Refasten Anti Theft Plate" },
  { code: "", description: "Replace Pin Swing Door Hinge" },
  { code: "", description: "Refasten Roller Door Seal" },
  { code: "", description: "Patch Left Inner Door Skin (5)" },
  { code: "", description: "Patch Right  Inner Door Skin (5)" },
  {
    code: "",
    description: "Replace Right Swing Door Panel  - Double Lock Rod     (  )",
  },
  {
    code: "",
    description: "Replace Left  Swing Door Panel  - Single Lock Rod     (  )",
  },
  {
    code: "",
    description: "Replace Right Swing Door Panel  - Single Lock Rod     (  )",
  },
  {
    code: "",
    description:
      "Replace Door Blank Composite  \n 1/2X49X11\n Replace Door Seal \n Replace Corner Tabs",
  },
  { code: "", description: "Section Corner ( w/Seals) Left  Door Panel" },
  { code: "", description: "Section Corner ( w/Seals) Right Door Panel" },
  { code: "", description: "Lubricate Lock Rod (s)  ." },
  { code: "", description: "Replace Hinge Pin" },
  { code: "", description: "Patch 2 ft X 1 ft Left Side Panel" },
  { code: "", description: "Refasten Left Side Panel" },
  { code: "", description: "Refasten Left Side Panel" },
  { code: "", description: "Seal Cut 4 Left Side Panel" },
  { code: "", description: "Section 1 ft Side Panel" },
  { code: "", description: "R & R 4' X 8' / Nose" },
  { code: "", description: "Patch  ft X 1 ft Left Trailer Skirts" },
  { code: "", description: "Patch  ft X 1 ft Right  Trailer Skirts" },
  { code: "", description: "Replace Left  Aero Flex Support Rod 68-5132-" },
  { code: "", description: "Replace Right Aero Flex Support Rod 68-5132-" },
  { code: "", description: "Replace  Swing Door Hinge Butt  / Bracket" },
  { code: "", description: "Replace Door Holdback Chain" },
  {
    code: "",
    description: "Removed + Straighten and Reinstalled Door Holdback Chain",
  },
  {
    code: "",
    description: "Replace Door Hold Back or Retainer Pigtail Style - 22-577",
  },
  { code: "", description: "Straighten Door Cam Keeper" },
  { code: "", description: "Straighten Right  Swing Door Hinge" },
  {
    code: "",
    description:
      "Replace   ___  FT'  Laminated Flooring (The first 4 ft   additional ft )",
  },
  { code: "", description: "Replaced Additional  Ft Laminate Flooring" },
  { code: "", description: "Refill Laminated Flooring" },
  { code: "", description: "Sweep Out Interior" },
  { code: "", description: "Fill Gouge Hard Wood Floor (  by ft )" },
  { code: "", description: "Refasten Threshold Plate" },
  { code: "", description: "Remove Nails Apitong Floor" },
  { code: "", description: "Replace Laminated Flooring" },
  { code: "", description: "Replace Laminated Flooring Additional by feet" },
  { code: "", description: "Replace Side Post" },
  { code: "", description: "Straighten Side Posts" },
  { code: "", description: "Replace Threshold Plate" },
  { code: "", description: "Patch  ft X  ft  Aluminum Roof" },
  { code: "", description: "Patch Aluminum Roof  ft X  ft" },
  { code: "", description: "Patch  ft X  ft Roof Aluminum" },
  { code: "", description: "Patch  ft X  ft Roof Aluminum" },
  { code: "", description: "Refasten Roof" },
  { code: "", description: "Patch  ft X  ft Roof Sheet Aluminum" },
  { code: "", description: "Patch  ft X   ft Roof Sheet Aluminum" },
  {
    code: "",
    description:
      "Reseal  ft X  ft  Aluminum Roof with Sealer extreme Rubberized",
  },
  { code: "", description: "Heat and Removed Old Seal  2 ft  + additional ft" },
  {
    code: "",
    description: "Reseal Aluminum Roof with Sealer  ft   Additional ft",
  },
  { code: "", description: "Patch 3.5 ft X  ft Aluminum Roof" },
  {
    code: "",
    description: "Reseal aluminum Roof Patch  (  additional patch )",
  },
  { code: "", description: "Patch  ft X  ft Aluminum Roof" },
  { code: "", description: "Reseal Nose Panel" },
  { code: "", description: "Patch Nose Panel" },
  { code: "", description: "Replace Roof Bow ( per unit )" },
  { code: "", description: "Refasten Roof Bow" },
  { code: "", description: "ft X  ft Roof Sheet ETR Translucent .75" },
  { code: "", description: "Reseal Nose Rail" },
  { code: "", description: "Patch Radius Corner with Metal   Repair Tape" },
  { code: "", description: "Heat + Removed Old Aluminum Tape and Sealer" },
  {
    code: "",
    description:
      "Patch Aluminum Roof with  self adhesive waterproof aluminum tape and Heat with Torch",
  },
  {
    code: "",
    description: "Repair Aluminum Roof with   Waterproof Roof Sealer",
  },
  { code: "", description: "Reseal Left  Roof Sheet-Aluminum" },
  { code: "", description: "Reseal Right Roof Sheet-Aluminum" },
  {
    code: "",
    description: "Replace 8 FT Section Rear Roof Sheet ETR Translucent .75",
  },
  { code: "", description: "Patch   ft X  ft Roof Sheet ETR Translucent .75" },
  { code: "", description: "Patch    ft X  ft Roof Sheet ETR Translucent .75" },
  { code: "", description: "Straighten Nose Rail Flange" },
  { code: "", description: "Reseal Roof Patch  4 ft    (additional  for ft)" },
  {
    code: "",
    description: "Reseal Section Front, rear Roof Sheet - Translucent",
  },
  { code: "", description: "Patch  ft X  ft Roof Sheet-Aluminum" },
  { code: "", description: "Patch  ft X  ft Roof Sheet Aluminum" },
  { code: "", description: "Straighten Roof Bow" },
  { code: "", description: "Patch 1 ft X  ft Roof Sheet- Translucent" },
  { code: "", description: "ft X  ft Roof Sheet ETR Translucent .75" },
  { code: "", description: "ft X  ft Roof Sheet ETR Translucent .75" },
  { code: "", description: "Reseal Front Roof  Sheet-Aluminum" },
  { code: "", description: "Patch  FT X  FT Roof Sheet ETR Translucent" },
  { code: "", description: "Patch  ft X  ft Roof Sheet Aluminum" },
  { code: "", description: "Patch  ft X  ft Roof Sheet ETR Translucent.75" },
  { code: "", description: "Patch 2 ft X 2 ft Roof Sheet ETR Translucent.75" },
  { code: "", description: "Replace Nose Panel Rivet (s)" },
  { code: "", description: "Patch  X  Aluminum Roof" },
  { code: "", description: "Reseal Left Corner Panel" },
  { code: "", description: "Reseal Right Corner Panel" },
  { code: "", description: "Patch Front Nose Panel  ft X  ft" },
  { code: "", description: "R&R Nose Scuff" },
  {
    code: "",
    description:
      "PM Maintenance Service \n Complete Lubrication and Grease \n Check and Air Up Tires",
  },
  { code: "", description: "Labor - Inspection (Grease /Lubrication)" },
  {
    code: "",
    description: "Truck # \nDriver Name : \n9 Days Inspection -  BIT",
  },
  { code: "", description: "Truck Repair" },
  { code: "", description: "Replace Battery ( Each )" },
  { code: "", description: "Replace Push  Pin  with Handle" },
  { code: "", description: "STRAIGHT AND WELD PIN HANDLE" },
  { code: "", description: "REPLACE PUSH  PIN HANDLE (Weld)" },
  { code: "", description: "STRAIGHT LATSH" },
  { code: "", description: "Replace Latch + Bolt + Nut" },
  { code: "", description: "Weld Latch Mount" },
  { code: "", description: "FABRICATE AND INSTALL HANDLE KEEPER MOUNT" },
  { code: "", description: "REPLACE TWIST LOCK PIN" },
  { code: "", description: "STRAIGHT AND WELD TWIST LOCK HANDLE" },
  { code: "", description: "REPLACE TWIST LOCK HANDLE" },
  { code: "", description: "Heat + Str Twist Lock Handle Bent" },
  { code: "", description: "Replace Twislock + Handle + Bolt and Nut" },
  { code: "", description: "Weld latch mount - Broken" },
  { code: "", description: "Weld Pin Latch - Missing" },
  {
    code: "",
    description:
      "Replace Twislock Kit  (Twislock + Handle + Space  + Pin Latch + Riser Block Housing + Shear Block + Detent Spring for Saftler )",
  },
  { code: "", description: "Replace Push Pin Handle Stop" },
  {
    code: "",
    description:
      "Removed Push Pin Housing (Broken                    and Install (Weld) new Push Pin +               Housing + Latch - Right Front",
  },
  { code: "", description: "Weld twist lock riser" },
  { code: "", description: "Realign Twislock out of position" },
  { code: "", description: "Replace:  Hook Latch Kit" },
  { code: "", description: "Straighten Twist lock Handle" },
  { code: "", description: "Replace Twist lock + Handle  + Bolt + Nut" },
  { code: "", description: "Straight Twist lock Handle" },
  { code: "", description: "Replace Snapper Pin \n 6653" },
  { code: "", description: "Replace Mudflap Mckinney" },
  { code: "", description: "Replace Twist lock Pin - Bolt on" },
  { code: "", description: "Replace Safety  Latch" },
  { code: "", description: "Replace Twist lock Handle Bolt On" },
  { code: "", description: "Straight Mudflap Bracket" },
  { code: "", description: "Replace Complete Twist lock Assembly" },
  { code: "", description: "Replace Safety  Latch Retainer" },
  { code: "", description: 'Replace Conspicuity Tape per 18" Piece (.8)' },
  { code: "", description: "Replace Tire Air Valve - Bad" },
  { code: "", description: "Remove Tires and Reinstall  ( SWAP )" },
  { code: "", description: "Replace Tire" },
  { code: "", description: "Replace Tire" },
  { code: "", description: "Repair Flat Tire" },
  { code: "", description: "Straight Rim  ( Bent )" },
  { code: "", description: "Replace  Spacer Wheel" },
  { code: "", description: "REMOVE + REPLACE + REMOUNT TIRE" },
  { code: "", description: "REMOVE + REPAIR + REMOUNT 1 TIRE" },
  { code: "", description: "Replace Tire + Rim" },
  { code: "", description: "Replace Trailer /Chassi  Tire" },
  { code: "", description: "Check and Air up all Tires" },
  { code: "", description: "Check Tires Tread Depth" },
  {
    code: "",
    description: "Removed and Reinstalled Tire (Improperly Installed)",
  },
  {
    code: "",
    description:
      "Check Tires and Check automatic system to fill the tires with air.",
  },
  { code: "", description: "Switch Tire (s) -" },
  { code: "", description: "Clean Up Hub Cap" },
  { code: "", description: "Wheel Inspection" },
  { code: "", description: "Replace 5th wheel Pull Handle   KIT-PUL-6L" },
  { code: "", description: "Replace stud Wheel + Wedge + Nuts ( Each)" },
  { code: "", description: "Replace Wedge Clamp" },
  {
    code: "",
    description:
      "Replace Oil Hubcap + Hubcap Gasket and Refill Oil \n34-49  STEMCO - Hub Cap 3449  \n Clean Oil of Rim Wheel",
  },
  { code: "", description: "Replace Wheel Seal Oil" },
  { code: "", description: "Repair Flat Tire" },
  { code: "", description: "Check and Air Up tires" },
  { code: "", description: "Replace Tire" },
  { code: "", description: "Replace Mounted Tire" },
  { code: "", description: 'Replace Wheel Valve Stem Tubeless 4 3/8" ' },
  {
    code: "",
    description: "Replace Wheel Clamp - Wedge \n Wheel Clamp",
  },
  { code: "", description: "Replace Wheel Stud  - One Pc for Every 3 Studs" },
  { code: "", description: "Replace Wheel Nut" },
  { code: "", description: "Replace tire (without tire repair)" },
  {
    code: "",
    description:
      "Remove Tires + Remove Brake Drum + Remove Brakes Shoes + Free Up Inner Scam Bushing - Frozen Left Front",
  },
  {
    code: "",
    description:
      "Remove Tires + Remove Brake Drum + Remove Brakes Shoes + Free Up Inner Scam Bushing - Frozen Left Rear",
  },
  {
    code: "",
    description:
      "Remove Tires + Remove Brake Drum + Remove Brakes Shoes + Free Up Inner Scam Bushing - Frozen Right  Rear",
  },
  {
    code: "",
    description:
      "Remove Tires + Remove Brake Drum + Remove Brakes Shoes + Free Up Inner Scam Bushing - Frozen Right  Rear",
  },
  { code: "", description: "Wheel End Inspection" },
  { code: "", description: "Wheel End Inspection" },
  {
    code: "",
    description: "Removed Hubcap + Repack Outer Bearing with new Grease",
  },
  { code: "", description: "Check Wheel Bearing / Jack Up" },
  { code: "", description: "Swap Tires (  each )" },
  { code: "", description: "Replace  Tires" },
  { code: "", description: "Repair Flat Tire" },
  { code: "", description: "Replace Wheel Tire Valve Stems" },
  { code: "", description: "Repair Tire 2 Patches" },
  { code: "", description: "Dismount Tire + Straight Rim + Remount Tire" },
  { code: "", description: "Replace Tire (Dismount and Remount)" },
  { code: "", description: "Replace Dual Stem Valve Caps" },
  { code: "", description: "Replace Tire  Stem Valve" },
  { code: "", description: "Replace with Refurbished Wheel" },
  { code: "", description: "Replace Wheel Stud  and Nut ( each )," },
  { code: "", description: "Installed Snow Chain Kit .\n QG2143" },
  { code: "", description: "Replace Hubcap Gasket" },
  {
    code: "",
    description:
      "Replace Wheel Seal \n Repack Bearings \n Repack Hub and Hubcap\n Replace Hubcap Gasket",
  },
  { code: "", description: "Replace Oil Wheel Seal" },
  { code: "", description: "Clean wheel Rim" },
  {
    code: "",
    description:
      "Replace Oil Hubcap 6 Holes + Hubcap Gasket and Refill Oil  \n34-49  STEMCO - Hub Cap",
  },
  { code: "", description: "Replace Hubcap and Gasket" },
  { code: "", description: "Reposition Tire (5)" },
  { code: "", description: "Replace Crank Handle + Bolt + Nut + Washers" },
  { code: "", description: "Replace Sand Shoes High  and Axle  -" },
  { code: "", description: "Replace Cushion Foot Kit   Sand Shoes" },
  { code: "", description: "Resecure Crank Handle with bolt , nut and washer" },
  {
    code: "",
    description: "Complete PM / BIT Inspection \nLube/Grease  Axles",
  },
  {
    code: "",
    description:
      "Complete Inspection FMCSA and PM Inspection \nLubrication /Grease Axles",
  },
  { code: "", description: "Patch Trlr Tracking Sys- Nose Panel ( each )" },
  {
    code: "",
    description: "Remove (Less than 12 X 12 ) Front Decals - Customer Decals",
  },
  {
    code: "",
    description:
      "Remove (Greater Than 12X12) 1ft X 2ft Front Decals - Customer  Decals",
  },
  {
    code: "",
    description: "Remove Interior  ft X  ft  Right Decals- Customer Decals",
  },
  {
    code: "",
    description: "Remove (Less than 12 X 12 ) Decals Rear  - Customer Decals",
  },
  {
    code: "",
    description: "Remove  Interior  ft X  ft  Right Decals- Customer Decals",
  },
  { code: "", description: "Remove Front Decals" },
  {
    code: "",
    description:
      "Replace Conspicuity Tape \n Clean Area to Install Conspicuity Tape",
  },
  { code: "", description: "Remove Exterior Left Graffiti ( Each feet)" },
  { code: "", description: "Remove Exterior Right  Graffiti ( Each feet)" },
  { code: "", description: "Replace Registration Holder" },
  { code: "", description: "Install Registration" },
  { code: "", description: "Replace Hub odometer" },
  {
    code: "",
    description:
      "Removed Trlr Tracking Antenna + Straighten Mount plate + Reinstalled and Refasten",
  },
  { code: "", description: "Remove Lock" },
  { code: "", description: "Clean Interior" },
  {
    code: "",
    description: "Remove Interior 1 ft X 1 ft Right Decals - Customer Decals",
  },
  {
    code: "",
    description: "Remove Interior  ft X  ft Rear Decals - Customer Decals",
  },
  { code: "", description: "Install Front Decals- Unit Numbers" },
  { code: "", description: "Install Rear Decals-Unit Numbers" },
  { code: "", description: "Removed E-Track (s) ( Each )" },
  { code: "", description: "Remove Hub odometer" },
  { code: "", description: "Reinstalled Smart Truck ARG" },
  { code: "", description: "Clean Glue" },
  { code: "", description: "Remove Customer  Unit Number and Decal" },
  { code: "", description: "Installed License Plate" },
  { code: "", description: "Remove Tape on all sides" },
  {
    code: "",
    description:
      "Removed Old License Plate + Installed New License Plate and Installed New Registration",
  },
  { code: "", description: "Run Parts" },
  { code: "", description: "Replace Registration Holder Cover" },
  { code: "", description: "Remove Trlr Tracking Sys-Basic ( each )" },
  {
    code: "",
    description: "Removed and Reinstalled Placard and Placard Holder",
  },
  { code: "", description: "Install  Front Placard Holder" },
  { code: "", description: "Install Placard" },
  { code: "", description: "Replace Mudflap  24 X 30" },
  { code: "", description: "Heat ,  Straight   Mudflap Bracket - Bent" },
  { code: "", description: "Reattach Left Rear Mudflap" },
  { code: "", description: "Reattach Right Rear Mudflap" },
  { code: "", description: "Replace 1 Rear Placard Holder" },
  {
    code: "",
    description:
      "Install Hazard Placard , Number-All Flip-File Placard, Blank Box Set, White Back Plate  ( Each Placard )",
  },
  { code: "", description: "Remove Glue from Panels" },
  { code: "", description: "Replace Mudflap Bracket" },
  { code: "", description: "Straighten Mudflap Bracket" },
  { code: "", description: "Replace Smart Truck Side Fairings" },
  { code: "", description: "Replace Trailer GPS" },
  { code: "", description: "Weld Mud Flap Bracket" },
  { code: "", description: "Replace License Plate" },
  {
    code: "",
    description: "Replace Hold Down Clip 2289-1   22891  Slider Clamps",
  },
  { code: "", description: "Replace Oval Lamp Mounting Bracket" },
  { code: "", description: "Replace ABS Sensor -  Left Front" },
  { code: "", description: "Replace ABS Sensor -  Left  Rear" },
  { code: "", description: "Replace ABS Sensor -  Right Front" },
  { code: "", description: "Replace ABS Sensor -  Right Rear" },
  { code: "", description: "Refasten ABS Harness Cable with plastic  Zip tie" },
  { code: "", description: "Check ABS System" },
  { code: "", description: "Replace ABS Computer" },
  { code: "", description: "Replace ABS Diagnostic Cable" },
  { code: "", description: "Reposition LF , RF ABS Sensor" },
  { code: "", description: "Check + Adjust and Lube 5th Wheel" },
  { code: "", description: "Replace Gladhand" },
  { code: "", description: "Resecure Air Hose" },
  { code: "", description: "Replace Bulkhead Fitting" },
  { code: "", description: "Replace 1 Air Valve" },
  { code: "", description: "Replace Brake Chamber" },
  {
    code: "",
    description: "Free up Scam Bushing - Frozen and Slack Adjuster ( each)",
  },
  { code: "", description: "Replace Slack Adjuster incl Brake Adjustment" },
  { code: "", description: "Replace Brake Hose" },
  { code: "", description: "Replace Air Fitting" },
  { code: "", description: "Replace Wheel Seal" },
  { code: "", description: "Replace Brakes Shoes per wheel" },
  { code: "", description: "Replace Air Tank" },
  { code: "", description: "Replace Hubcap" },
  { code: "", description: "Replace Petcock" },
  { code: "", description: "Free Up Slack Adjuster and/or Cam Shaft (each )" },
  { code: "", description: "Replace Brakes Shoes Complete (All Wheels) -" },
  { code: "", description: "Replace Brake Drum" },
  { code: "", description: "Repair Air Line" },
  { code: "", description: "Resecure Bulkhead Fitting" },
  { code: "", description: "Heat + Free up Clevis and Pins - Frozen" },
  { code: "", description: "Trace and Repair Air System" },
  { code: "", description: "Replace Push Rod Clevis + Pins" },
  { code: "", description: "Replace Plug Fitting" },
  { code: "", description: "Replace Swinger Gladhand" },
  {
    code: "",
    description: "Install hose separator -  Spacer hoses (1-4 per piece )",
  },
  { code: "", description: "Free up Brakes Shoes - Frozen" },
  {
    code: "",
    description:
      "Resecure Push Rod Nut  \n Refasten Brake Chamber Jam Nut",
  },
  { code: "", description: "Replace Bulk Head Fitting" },
  { code: "", description: "Check and Adjust Brakes Front Axle / Rear Axle" },
  { code: "", description: "Roadability Inspection" },
  {
    code: "",
    description:
      "Tri Axle FMCSA Annual Inspection \n Adjust Brakes \n Lubricate Axles, Landing Legs and Safety Devices",
  },
  { code: "", description: "Replace Document   Holder" },
  { code: "", description: "Replace Federal Sticker / FMCSA Decal" },
  { code: "", description: "Straight and Weld Front Bolster" },
  { code: "", description: "Replace Slider Handle" },
  { code: "", description: "Replace Marker Light with Flange" },
  { code: "", description: "Replace Marker Light  Grommet 2'" },
  { code: "", description: "Replace 7 way Receptacle" },
  { code: "", description: "Replace 7 way  16-724" },
  { code: "", description: "Replace Pigtail plug 2 way" },
  { code: "", description: "Replace Pigtail Plug 3 way" },
  {
    code: "",
    description:
      "Trace and Repair ABS Problem  \n Troubleshoot ABS System",
  },
  { code: "", description: "Replace License Plate" },
  { code: "", description: "Reconnect Stop Lights" },
  { code: "", description: "Reconnect  Marker Lights ( Each )" },
  { code: "", description: "Shipping and Handle Fees" },
  { code: "", description: "Heat + Straighten Cross Member" },
  { code: "", description: "Resecure u bolt - Spring Bolt" },
  { code: "", description: "REPLACE SLIDER LOCK PIN" },
  { code: "", description: "REPLACE SLIDER STOP 1" },
  { code: "", description: "STRAIGHT SLIDER GUIDE" },
  { code: "", description: "STRAIGHT AND WELD CROSS MEMBER" },
  { code: "", description: "Heat + Straight Slider Pin Arm" },
  { code: "", description: "STRAIGHT SLIDER HANDLE" },
  { code: "", description: "STRAIGHT FRAME AS PER DAMAGE" },
  {
    code: "",
    description: "Weld Chassi Bolster Right Side and Left Side - Cracked",
  },
  { code: "", description: "Straight Bolster Housing Light" },
  { code: "", description: "Heat + Str + Weld ICC Bumper - Broken" },
  { code: "", description: "Reweld Cross Member" },
  { code: "", description: "Heat + Straight + Weld Tail Light Bracket" },
  {
    code: "",
    description:
      "Heat + Str Upright  + Replace Gussets - Bent\r\n Replace Step ICC Bumper - Bent",
  },
  { code: "", description: "Straighten  Main Frame - Bent" },
  { code: "", description: "Replace Slider Handle" },
  {
    code: "",
    description:
      "Replace Rubber Bumper  B45    \n Replace 4 Bolts + Nuts + Flat Washers",
  },
  { code: "", description: "Sweep Out" },
  { code: "", description: "Bridge Toll" },
  { code: "", description: "Removed + Remount and  Reinstall Tire ( each)" },
  { code: "", description: "Remove  Electronic Log Book" },
  { code: "", description: "Labor Replace Wiper Blades ( each )" },
  { code: "", description: "Truck # \n PM DRY No Filter /Fluid Change" },
  {
    code: "",
    description:
      "Replace Complete Air Lines and Electrical Power Cord  \n Reinstalled Air Lines Holder Bracket \n Reinstalled Gladhands \n Reinstalled Air Lines Holder Spring \n Reinstalled  Air Fittings \n Resecure Air Lines  with Zip tie",
  },
];

export default services;
