const customer = [
  {
    name: "002  P and R",
    phoneNumber: "Phone: 510 8391602",
    email:
      "lorri@pandrtrucking.com,more1023@aol.com,jhnaprryn2@aol.com,aurora@pandrtrucking.com",
    fullName: "Lorri",
    billingAdress:
      "P&R Trucking Inc.\n3690 Sprig Drive Suite B\nBenicia CA 94510",
    shippingAdress:
      "1 Martin Luther King Jr Way\noakland California 94607\nUSA",
  },
  {
    name: "48 forty Solutions",
    email: "ian.high@48forty.com",
  },
  {
    name: "98897021.3789/.27/*MC KINNEY - Hayward HDJYTJU7IE78UHG BO|\\",
  },
  {
    name: "A & G Transport",
    phoneNumber: "\nMobile: 510-943-2480",
    email: "dispatch.agt@gmail.com",
    fullName: "Amarjit Guraya",
    billingAdress: "30250 Willowbrook Rd.\nHayward CA 94544\nUSA",
  },
  {
    name: "A. Tasteful Affair",
    phoneNumber: "Phone: (925) 550-3935",
    email: "peggy@atasteful-affair.com",
    fullName: "Peggy Welch",
    billingAdress: "3370 Hopyard Rd.\nPleasanton California 94588\nUSA",
    shippingAdress: "3370 Hopyard Rd.\nPleasanton California 94588\nUSA",
  },
  {
    name: "AAA Express",
    phoneNumber: "Mobile: 5107095488",
    email: "oak@aaaexpressco.com",
    billingAdress: "3738 Horner  Street\nUnion City CA 94587",
    shippingAdress: "3738 Horner  Street\nUnion City CA 94587",
  },
  {
    name: "ACMS Group C/O P & G Power Corp.",
    phoneNumber: "Phone: 562-577-0139",
    email: "victor@pgcorp.us,lbussey@acmsgroup.com",
    fullName: "Mrs Laura Bussey",
    billingAdress: "10769 Broadway  # 333\nCrown Point IN 46307",
    shippingAdress: "10769 Broadway  # 333\nCrown Point IN 46307",
  },
  {
    name: "AE Trading",
    phoneNumber: "Mobile: (415) 318-0109",
    email: "jenmei79@yahoo.com",
    fullName: "Jen",
    billingAdress: "AE",
  },
  {
    name: "AG  Trading Company",
    phoneNumber: "Phone: 415 318 0109",
    email: "jenmei79@yahoo.com",
    fullName: "Jen",
    billingAdress: "616   16th Ave\nSan Francisco CA 94118",
    shippingAdress: "616   16th Ave\nSan Francisco CA 94118",
  },
  {
    name: "Airco Gases, Inc",
    phoneNumber: "Phone: (510) 867-1234",
    email: "marvin@aircogases.com",
    billingAdress:
      "3880 Irving Blvd\nDallas, TX 75247\nLivermore California 94550\nUSA",
    shippingAdress:
      "3880 Irving Blvd\nDallas, TX 75247\nLivermore California 94550\nUSA",
  },
  {
    name: "AKIN TRUCKING COMPANY",
    phoneNumber: "Phone: 5104366222",
    email: "pinto4u@gmail.com",
    billingAdress: "P.O. BOX 22115\nOakland CA 94623",
    shippingAdress: "P.O. BOX 22115\nOakland CA 94623",
  },
  {
    name: "Alexander's Mobility Services",
    phoneNumber: "Phone: 5105849182\n",
    email: "jlwilliams@alexanders.net",
    fullName: "Jimmy L Williams",
    billingAdress: "3528 Arden Road\nHayward CA 94545",
    shippingAdress: "3528 Arden Road\nHayward CA 94545",
  },
  {
    name: "ALL MODULAR SYSTEMS",
    phoneNumber: "\nMobile: (510) 294-0292",
    email: "Narcisol@allmodularsystems.com, leslie@allmodularsystems.com",
    billingAdress: "30826 Santana Street\nHayward California 94544\nUSA",
    shippingAdress: "30826 Santana Street\nHayward California 94544\nUSA",
  },
  {
    name: "ALL PRO FACILITY",
    email: "privera@baycontract.com",
  },
  {
    name: "Allied Box Co",
    phoneNumber: "Mobile: (415) 559-1305",
    email: "abiagi@alliedbox.com",
    fullName: "Angelo Biagi",
    billingAdress: "1015 Chesley Ave.\nRichmond California 94801\nUSA",
    shippingAdress: "1015 Chesley Ave.\nRichmond California 94801\nUSA",
  },
  {
    name: "Alt Intermodal Inc.",
    phoneNumber: "Phone: 5108670000",
    email: "noel@altmodal.com",
    fullName: "Noel",
    billingAdress: "675 Hegenberger Road\nSuite 201\nOakland CA 94621",
    shippingAdress: "675 Hegenberger Road\nSuite 201\nOakland CA 94621",
  },
  {
    name: "ALTT",
    phoneNumber: "Phone: 2094965291",
    fullName: "MANUEL",
  },
  {
    name: "American Roadway",
    phoneNumber: "Phone: (415) 286-3916",
    fullName: "Leo",
    billingAdress:
      "1139 Palou Avenue\nSan Francisco, CA  94124   USA\nsan francisco ca 94124",
    shippingAdress:
      "1139 Palou Avenue\nSan Francisco, CA  94124   USA\nsan francisco ca 94124",
  },
  {
    name: "American Transportation",
    phoneNumber: "Phone: 5108721202",
    email: "breyno@atsicontainer.com",
    fullName: "Allen Reyno",
  },
  {
    name: "anthony imperial",
    email: "Anthony.imperial@sbcglobal.net",
    fullName: "anthony imperial",
    billingAdress: "1300 25th st Unit C\nSan francisco",
    shippingAdress: "1300 25th st Unit C\nSan francisco",
  },
  {
    name: "Antonini",
    phoneNumber: "Phone: 2094664900",
    email: "dispatch@antoniniusa.com",
    fullName: "Cam",
    billingAdress: "PO Box 8468\nStockton CA 95208",
    shippingAdress: "PO Box 8468\nStockton CA 95208",
  },
  {
    name: "AP Trucking INC.",
    phoneNumber: "Phone: (510) 201-0092",
    email: "sohitony@gmail.com",
    billingAdress: "1432 Maritime Street\nOakland California",
    shippingAdress: "1432 Maritime Street\nOakland California",
  },
  {
    name: "Apex Maritime Co Inc.",
    phoneNumber: "Phone: (650) 589-2575",
    email: "judy.tsui@apexshipping.com",
    fullName: "Judy Tsui",
    billingAdress: "411 Airport Boulevard\nBurlingame California 94010\nUSA",
    shippingAdress: "411 Airport Boulevard\nBurlingame California 94010\nUSA",
  },
  {
    name: "Apex Service",
    phoneNumber: "Phone: (925) 596-3732",
    fullName: "Jorge",
    billingAdress: "1541 doolittler dr\nsan leandro ca 94577",
    shippingAdress: "1541 doolittler dr\nsan leandro ca 94577",
  },
  {
    name: "archila's trucking",
    phoneNumber: "Phone: 4159138674",
    email: "archilatrucking@gmail.com",
    fullName: "jonathan vargas",
    billingAdress: "453 ROADRUNNER DR\nPATTERSON CA 95363",
  },
  {
    name: "AV TRUCKING COMPANY INC.",
    phoneNumber: "Phone: 5106280142",
    email: "avtruckingco@gmail.com",
    fullName: "Singh Vishavdeep",
    billingAdress: "1155 Third St.  Suite 300\nOakland CA 94607",
    shippingAdress: "1155 Third St.  Suite 300\nOakland CA 94607",
  },
  {
    name: "BAL TRUCKING",
    phoneNumber: "Phone: 5104027371",
    email: "singh.palvir@yahoo.com",
    fullName: "Mr. Singh Palvir",
    billingAdress: "Bal Trucking .",
  },
  {
    name: "BATR",
    phoneNumber: "\nMobile: 2096132068",
    email: "linus@batr.us",
    fullName: "Mr. Linus Schlumpberger",
    billingAdress: "22409 Thunderbird Place\nHayward CA 94545",
    shippingAdress:
      "Bay Area Transport Refrigeration\r\nMr. Linus Schlumpberger\r\n22409 Thunderbird Place\r\nHayward, CA 94545",
  },
  {
    name: "Bay Area Intermodal Services Inc",
    phoneNumber: "\nMobile: 9255700018",
    email: "dispatch@bayareaintermodal.com",
    fullName: "Lisa Fonseca",
    billingAdress: "2850 Cordelia Road Ste 110\nFairfield CA 94534",
    shippingAdress:
      "Lisa Fonseca\n2850 Cordelia Road Ste 110\nFairfield CA 94534",
  },
  {
    name: "Bay Area Trucking",
    phoneNumber: "\nMobile: 5108309514",
    email: "bayareadispatch@yahoo.com",
    fullName: "Bobby",
    billingAdress: "7172 Regional St.\r\n# 419\r\nca\nDublin CA 94568",
    shippingAdress:
      "Bay Area Trucking\r\n7172 Regional St.\r\n# 419\r\nDublin , CA 94568",
  },
  {
    name: "BELNOZA TRANSPORTS",
    phoneNumber: "Mobile: 5102589377",
    email: "belnoza@mail.com",
    fullName: "Ronaldo",
    billingAdress: "111 Easter CT\r\nCalifornia\nVallejo CA 94589\nUSA",
  },
  {
    name: "Benz Transportation",
    phoneNumber: "Phone: (510) 264-9822",
    email: "stevie@benztransport.com",
    billingAdress: "23575 Canot Blvd Suite 213\nHayward California 94545\nUSA",
    shippingAdress: "23575 Canot Blvd Suite 213\nHayward California 94545\nUSA",
  },
  {
    name: "Bering Sea Logistics",
    email: "beringsealogisticsinc@gmail.com",
    billingAdress: "212 9th Street, #310c\nOakland CA 94607",
    shippingAdress: "212 9th Street, #310c\nOakland CA 94607",
  },
  {
    name: "Berkeley Farms",
    phoneNumber: "\nMobile: 5103424149",
    email: "gary_finch@deanfoods.com",
    fullName: "Gary Finch",
    billingAdress: "25500 Clawitter Road\nHayward CA 94545",
    shippingAdress: "25500 Clawiter Road\nHayward CA 94545",
  },
  {
    name: "Berkeley Warehouse",
    phoneNumber: "\nMobile: (510) 812-7023",
    email: "berkwhse@earthlink.net",
    billingAdress: "1920 Second St.\nBerkeley California 94710\nUSA",
    shippingAdress: "1920 Second St.\nBerkeley California 94710\nUSA",
  },
  {
    name: "Best Buy Trucking",
    phoneNumber: "Phone: 510-201 9077",
    email: "cintia@crgcos.com",
    fullName: "Mr. Kevin Sandhu",
    billingAdress:
      "30042 Mission Blvd # 121-333\r\nCalifornia\nHayward CA 94544",
  },
  {
    name: "Best Drayage Company",
    phoneNumber: "Phone: (209) 624-8564",
    email:
      "dispatch@bestdrayage.com,cpeters@bestdrayage.com,adabney@bestdrayagecompany.com",
    billingAdress: "P.O. Box 449\nGustine California 95322\nUSA",
    shippingAdress: "P.O. Box 449\nGustine California 95322\nUSA",
  },
  {
    name: "Big D Moving & Trucking",
    phoneNumber: "Phone: 5109876059",
    fullName: "Henry Hughes",
    billingAdress: "274 Sunset Ave.\nSuisun CA 94585",
    shippingAdress:
      "Big D Moving & Trucking\r\nHenry Hughes\r\n274 Sunset Ave.\r\nSuisun, CA 94585",
  },
  {
    name: "blue raven oil",
    phoneNumber: "Phone: (701) 339-1567",
    email: "blueravenoilllc@gmail.com",
    fullName: "ricardo",
    billingAdress: "po box 1516 parinson Ca 945363",
  },
  {
    name: "BOBAC",
    phoneNumber: "\nMobile: 5109122700",
    email: "Bob@bobaccfs.com",
    fullName: "Mr Bob Haydari",
    billingAdress: "300 A. Ave\nAlameda ca 94501",
    shippingAdress: "300 A. Ave\nAlameda ca 94501",
  },
  {
    name: "Break Time",
  },
  {
    name: "Bryan",
    phoneNumber: "Mobile: (510) 631-4469",
    email: "brianl@iocompanies.com",
    fullName: "Bryan",
  },
  {
    name: "C P Carriers",
    phoneNumber: "\nMobile: (510) 377-4560",
    email: "cp.carrierinc@yahoo.com",
    fullName: "Mr. Part Singh",
    billingAdress: "CP Carrier Inc\r\nOakland,\n2585 Buna St CA 94607",
    shippingAdress: "CP Carrier Inc\r\n2585 Buna St, CA 94607\r\nusa",
  },
  {
    name: "CALIFORNIA MULTIMODAL LLC",
    phoneNumber: "Phone: 5104462246",
    email: "mike.michel@cmiamerica.com",
    fullName: "CALIFORNIA MULTIMODAL LLC",
    billingAdress: "375 Maritime Street\nOakland CA 94607\nUSA",
    shippingAdress:
      "CALIFORNIA MULTIMODAL LLC\r\n375 Maritime Street\r\nOakland, CA 94607\r\nUSA",
  },
  {
    name: "Capital Containers",
    phoneNumber: "Phone: (916) 560-9081",
    email: "capitalcontainers@gmail.com, susanmarkell8@gmail.com",
    billingAdress:
      "720 Sutter Avenue\r\nWest Sacramento, Ca 95691\r\n916-371-4141\r\nCalifornia\nSacramento CA 95691",
    shippingAdress:
      "720 Sutter Avenue\r\nWest Sacramento, Ca 95691\r\n916-371-4141\r\nFax: 866-506-3035",
  },
  {
    name: "Capital River Group, LLC",
    phoneNumber: "Phone: 209 466-3333",
    email: "ACCOUNTING@CRGCOS.COM,adam@crgcos.com",
    billingAdress: "807 Cromwell Ave.\nStockton CA 95203",
    shippingAdress:
      "CAPITAL RIVER GROUP, LLC\r\n807 Cromwell Ave.\r\nStockton, CA 95203",
  },
  {
    name: "Cargo Bay Trucking",
    phoneNumber: "Phone: 5104516800",
    email: "jag@cargobayinc.com",
    billingAdress: "1155  3rd St  #200\nOakland CA 94607",
    shippingAdress: "1155  3rd St  #200\nOakland CA 94607",
  },
  {
    name: "Carlos Villeda",
    phoneNumber: "Phone: (925) 565-3723",
    email: "carlvill25@yahoo.com",
  },
  {
    name: "Cash Payment",
    email: "usman200GB@gmail.com",
  },
  {
    name: "CDH TRUCKING",
    fullName: "CHRISTIAN HERNANDEZ",
  },
  {
    name: "Central Cal Transportation",
    phoneNumber: "Phone: 5594764416",
    email: "APINVOICES@RRINTERMODAL.COM, Tara.Smith@rrintermodal.com",
    billingAdress: "3032 E. Central Ave.\nFresno CA 93725",
    shippingAdress: "Oakland\nOakland California 94607\nUSA",
  },
  {
    name: "Central Transport LLC",
    phoneNumber: "5869397000 ext2420",
    email: "apaymaint@centraltransport.com,Roadservice@centraltransport.com",
    billingAdress: "12225 Stephens Rd.\nWarren Mi 48089\nUSA",
    shippingAdress: "2256 Claremont Ct,\nHayward CA 94545\nUSA",
  },
  {
    name: "Clayton  Transportation LLC",
    phoneNumber: "Mobile: 9252125177",
    email: "ha@claytonlogistics.com",
    billingAdress: "370 8th Ave,\nOakland CA 94606",
    shippingAdress:
      "Clayton Transportation  LLC\r\n370 8th Ave,\r\nOakland, CA 94606",
  },
  {
    name: "Col Express",
    email: "dispatch@colxpress.com",
  },
  {
    name: "Cold Ruff Expres",
  },
  {
    name: "Cold Rush Express",
    email: "bill.cooke@coldrushexpress.com",
  },
  {
    name: "colorama nursery",
    phoneNumber: "Phone: (629) 945-5201",
    email: "jose@coloramanursery.com",
    fullName: "jose gonzalez",
    billingAdress: "1025 north todd ave asusa ca 91702",
  },
  {
    name: "COMMON TRANSPORT",
    phoneNumber: "Phone: 5306354060",
    email: "commontransport2014@gmail.com",
    billingAdress: "606 Anna Dr\nyuba city CA 95993",
    shippingAdress: "606 Anna Dr\nyuba city CA 95993",
  },
  {
    name: "Concentric ,  LLC",
    phoneNumber: "Phone: (530) 304-9679",
    email: "ap@concentricusa.com,jennifer.horstman@concentricusa.com",
    billingAdress: "3235 Levis Commons Blvd\nPerrysburg Ohio 43551\nUSA",
    shippingAdress: "3235 Levis Commons Blvd\nPerrysburg Ohio 43551\nUSA",
  },
  {
    name: "Concrete Sawing",
    phoneNumber: "Phone: (408) 507-6603",
    fullName: "Larry",
    billingAdress: "767 Pollard Rd\nLos Gatos California 95032",
    shippingAdress: "767 Pollard Rd\nLos Gatos California 95032",
  },
  {
    name: "Conde Nast Magaz",
  },
  {
    name: "Container Freight Line",
    phoneNumber: "Phone: (559) 801-1160",
    email: "Melissa.cfl@yahoo.com",
    fullName: "Melissa Mata",
  },
  {
    name: "COOL BULL EXPRESS INC",
    phoneNumber: "Phone: 5104832936",
    email: "coolbullexpress@gmail.com",
    fullName: "Savill Tse",
    billingAdress: "496 Hester St\nSan Leandro CA 94577",
    shippingAdress:
      "COOL BULL EXPRESS INC\r\nSavill Tse\r\n496 Hester St\r\nSan Leandro, CA 94577",
  },
  {
    name: "Cool Port Management LLC",
    email: "kmcintosh@dreisbach.com,Apinvoices@dreisbach.com",
    billingAdress: "575 Maritime St.\nOakland California 94607\nUSA",
    shippingAdress: "575 Maritime St.\nOakland California 94607\nUSA",
  },
  {
    name: "CSA MAINTENANCE SERVICE INC",
    phoneNumber: "Mobile: 5107197740",
    email: "mjames1409@att.net",
    fullName: "Michael James",
    billingAdress: "1113 Vista Point Lane\nConcord CA 94521",
    shippingAdress: "1113 Vista Point Lane\nConcord CA 94521",
  },
  {
    name: "D.R. Trucking & Warehousing Inc.",
    phoneNumber: "Phone: 5103533853",
    email: "jorgeb.DRT@gmail.com",
    fullName: "Jorge Baraibar",
    billingAdress: "1975 West Avenue 140th\nSan Leandro CA 94577",
    shippingAdress: "1975 West Avenue 140th\nSan Leandro CA 94577",
  },
  {
    name: "Day to Day Logistics Inc.",
    email: "tracking@daytodaylogistics.com,dispatch@daytodaylogistics.com",
    billingAdress: "425 Gibraltor Drive\nMississauga Ontario L5T2S9\nCanada",
    shippingAdress: "425 Gibraltor Drive\nMississauga Ontario L5T2S9\nCanada",
  },
  {
    name: "DCLI",
    phoneNumber: "Mobile: (510) 812-9818",
    email: "Thomas.McClean@dcli.com,Patrick.Sharer@dcli.com",
    billingAdress: "PO Box 1065\nBenicia California 64510\nUSA",
    shippingAdress: "PO Box 1065\nBenicia California 64510\nUSA",
  },
  {
    name: "DCLI Roadservice",
    phoneNumber: "Phone: (704) 256-8067",
    email:
      "roadservice@dcli.com,Thomas.McClean@dcli.com,Patrick.Sharer@dcli.com",
    billingAdress:
      "3525 Whitehall Park Dr.\nSuite 400\nCharlotte North Caroline 28273\nUSA",
    shippingAdress:
      "3525 Whitehall Park Dr.\nSuite 400\nCharlotte North Caroline 28273\nUSA",
  },
  {
    name: "Delo Transportation",
    phoneNumber: "\nMobile: (408) 931-4635",
    email: "dispatch@delotransportation.com",
    fullName: "Robert",
    billingAdress: "232 Calcite Ave.\nLathrop California",
    shippingAdress: "232 Calcite Ave.\nLathrop California",
  },
  {
    name: "Dependable Highway Express",
    phoneNumber: "Mobile: 9163026167 james",
    email: "Avikash.Singh@godependable.com",
    fullName: "Avikash Singh",
    billingAdress: "3199 Alvarado Road,\nSan Leandro CA 94577",
  },
  {
    name: "Deposit ID",
  },
  {
    name: "DNH Carriers Inc",
    phoneNumber: "Mobile: 510-504-4908",
    email: "dnhcarriers@sbcglobal.net",
    fullName: "Dave",
    billingAdress: "4455 Utah  Drive\r\nCalifornia\nEl Sobrante CA 94820\nUSA",
  },
  {
    name: "Downtime Fleet Management Services",
    phoneNumber: "Phone: (866) 965-9288",
    email: "documents@downtimefleet.com",
    billingAdress: "1468  US-80\nPooler georgia 31322\nUSA",
    shippingAdress: "1468  US-80\nPooler georgia 31322\nUSA",
  },
  {
    name: "DREISBACH",
    phoneNumber: "\nMobile: 2093461073",
    email: "rita@dreisbach.com,steve@dreisbach.com",
    billingAdress: "2530 East Eleventh Street\nP.O. Box 7509\nOakland CA 94601",
    shippingAdress:
      "2530 East Eleventh Street\nP.O. Box 7509\nOakland CA 94601",
  },
  {
    name: "Duong Trucking",
    email: "kelvin.pham@shippertransport.com",
  },
  {
    name: "E. Marquez Transport",
    phoneNumber: "Phone: (626) 437-7976",
    email: "emarqueztransport@hotmail.com",
  },
  {
    name: "East Bay Trucking Corp.",
    phoneNumber: "Mobile: 9255841940",
    email: "occidenteex@yahoo.com",
    billingAdress: "1728 Petit Peak Ct.\nAntioch CA 94531",
    shippingAdress:
      "East Bay Trucking Corp.\r\n1728 Petit Peak Ct.\r\nAntioch, CA 94531",
  },
  {
    name: "Eduardo Vargas",
    phoneNumber: "\nMobile: (510) 502-0912",
    email: "santos@blueseatruckings.com",
    fullName: "Eduardo Vargas",
    billingAdress: "8278 S. Wolfe.  Road\nFrench Camp California 95231\nUSA",
  },
  {
    name: "Electrical Products & Control",
    phoneNumber: "\nMobile: (408) 218-9101",
    email: "frank@epandc.com",
    fullName: "Frank Taormina",
    billingAdress: "346 Charcot Avenue\nSan Jose California 95131\nUSA",
  },
  {
    name: "EXITRUCKING",
  },
  {
    name: "Express Logistics Solutions",
    phoneNumber: "Phone: 5102240036",
    email: "dispatch@expresslogisticssolutions.com",
    fullName: "Shanti Campbell",
    billingAdress: "2336 Merced Street\nSan Leandro CA 94577",
    shippingAdress: "2336 Merced Street\nSan Leandro CA 94577",
  },
  {
    name: "F R Transport",
    phoneNumber: "Phone: 5106720236",
    email: "frttrucking@gmail.com",
    fullName: "Mr. Frankie Rodriguez",
    billingAdress: "7700 Edgewater Dr.\nOakland CA",
    shippingAdress: "F R Transport\r\n7700 Edgewater Dr.\r\nOakland, CA",
  },
  {
    name: "Fargo Trucking & Logistics Corp. Inc. dba FTLC Inc.",
    phoneNumber: "Phone: (510)834-0988",
    email: "vincent@fargo-trucking.com",
    billingAdress:
      "2900 MAIN  St, Building  140 Suite \nAlameda , CA  94501\n3201",
    shippingAdress:
      "FTLC Inc.\n2900 MAIN  St, Building  140 Suite 3201\nAlameda , CA  94501",
  },
  {
    name: "FAST WAY XPRESS",
    phoneNumber: "\nMobile: 5103772620",
    email: "paul@fastwayxpress.net,dil@fastwayxpress.net",
    billingAdress: "1425 MARITIME\noakland CA 94545",
  },
  {
    name: "FASTENAL",
  },
  {
    name: "Federal Express",
    phoneNumber: "Phone: (800) 447-8140",
    email: "Maint.coord@fedex.com",
    billingAdress: "2200 Forward Dr.\nHarrison AR 72601",
  },
  {
    name: "Federal Express Livermore",
    phoneNumber: "Mobile: (209) 482-8312",
    email:
      "scdistrict@fedex.com, David.Leach@fedex.com, Tony.Delalluz@fedex.com",
    fullName: "Jerry Ecklund",
    billingAdress: "225 Greenville road\nLivermore california 94551\nUSA",
    shippingAdress: "225 Greenville road\nLivermore california 94551\nUSA",
  },
  {
    name: "Federal Express San Jose",
    phoneNumber: "Mobile: 408 -945-0162",
    email: "bert.flores@fedex.com,scdistrict@fedex.com,david.leach@fedex.com",
    billingAdress: "3425 Victor St.\nSanta Clara California 95054\nUSA",
    shippingAdress: "3425 Victor St.\nSanta Clara California 95054\nUSA",
  },
  {
    name: "Fedex Hayward",
    phoneNumber: "Mobile: (510) 203-7257",
    email: "scdistrict@fedex.com,david.leach@fedex.com,jose.a.diaz@fedex.com",
    billingAdress:
      "2200 Foward Dr.\nHarrison Arizona 72601\nUSA , Vendor # OAK09",
  },
  {
    name: "Fleet Net America",
    phoneNumber: "Phone: (800) 438-8961",
    email: "FNABilling@fleetnetamerica.com, Taylorb@fleetnetamerica.com",
    billingAdress:
      "PO Box 970\n300 Commerce Drive\nCherryville North Caroline 28021\nUSA",
  },
  {
    name: "FLEXIVAN",
    phoneNumber: "Phone: (480) 581-9879",
    email: "SSTANLEY@FLEXIVAN.COM",
    billingAdress: "7320 E. Butherus Dr. #201\nScottsdale, AZ  85260",
    shippingAdress: "7320 E. Butherus Dr. #201\nScottsdale, AZ  85260",
  },
  {
    name: "Flying R Express",
    phoneNumber: "Phone: 9169125875",
    email: "flying-r-express@outlook.com",
    fullName: "Randy Rankin",
    billingAdress: "5133 Laurelview Ave.\nCarlmichael CA 95608",
    shippingAdress:
      "Flying R Express\r\nRandy Rankin\r\n5133 Laurelview Ave.\r\nCarlmichael, CA 95608",
  },
  {
    name: "Foward Logistics",
    phoneNumber: "Mobile: 6503330127",
    email: "filex@fowardlogistics.net",
  },
  {
    name: "Foward Trans Inc",
    phoneNumber: "Phone: (510) 314-1280",
    fullName: "Jasvinder",
  },
  {
    name: "Freedom Medical Inc",
    phoneNumber: "Phone: (510) 706-9458",
    billingAdress: "20981 Cabot Blvd\nHayward California 94545\nUSA",
    shippingAdress: "20981 Cabot Blvd\nHayward California 94545\nUSA",
  },
  {
    name: "Freight King Inc",
    phoneNumber: "\n (408) 425-1616",
    email: "info@freightking.us",
    fullName: "Kuldip Badwal",
    billingAdress: "1143 Pacific St, \nUnion City, CA 94587",
    shippingAdress: "1143 Pacific St, \nUnion City, CA 94587",
  },
  {
    name: "freight line express",
    phoneNumber: "Phone: 6505529928\n",
    email: "jay@freightlineexpress.com,dispatch@freightlineexpress.com",
    fullName: "Shelly Tse",
    billingAdress: "1601 BAYSHORE HWY STE 341\nBURLINGAME CA 94010",
    shippingAdress:
      "Shelly Tse\n1601 BAYSHORE HWY STE 341\nBURLINGAME CA 94010",
  },
  {
    name: "FXI",
    phoneNumber: "Mobile: (510) 750-5431",
    email: "tthompson@fxi.com",
    fullName: "Terry Thompson",
    billingAdress: "2451 Polvorosa Dr.\nSan Leandro California 94577\nUSA",
    shippingAdress: "2451 Polvorosa Dr.\nSan Leandro California 94577\nUSA",
  },
  {
    name: "FYXFLEET",
    phoneNumber: "Phone: (800) 888-1001\n",
    email: "po@fyxfleet.com",
    billingAdress:
      "500 Meijer Drive, Suite 300\nFlorence Kentucky 41042\nUSA      Vendor # 35209",
    shippingAdress: "California\nUSA",
  },
  {
    name: "Gadner Trucking",
    fullName: "Coody",
    billingAdress: "2577 West Yosemite Ave.\nManteca CA 95337",
    shippingAdress: "2577 West Yosemite Ave.\nManteca CA 95337",
  },
  {
    name: "Gangyuan Xie",
  },
  {
    name: "Gary Aragon",
    fullName: "Gary Aragon",
  },
  {
    name: "Genesis  Intermodal",
    phoneNumber: "Mobile: 209-4239-816",
    email: "stocktondispatch@emailgenesis.com,fpennington@emailgenesis.com",
    fullName: "Heather Smith",
    billingAdress:
      "Genesis Intermodal Delivery\r\n250 cherry lane suite 113\r\nCalifornia\nManteca 95336",
    shippingAdress:
      "Genesis  Intermodal\r\n250 cherry lane suite 113\r\nManteca, California 95336",
  },
  {
    name: "Geneva",
    phoneNumber: "Mobile: 14152983012",
    email: "tim@genevagrowers.com",
    fullName: "Tim Baumsteiger",
    billingAdress: "2050 Galvez Avenue\r\nCalifornia\nSan Francisco CA 94124",
    shippingAdress:
      "Geneva Truck Service\r\nTim Baumsteiger\r\n2050 Galvez Avenue\r\nSan Francisco , California 94124",
  },
  {
    name: "Geneva9/699",
  },
  {
    name: "Geological Design",
    phoneNumber: "Mobile: (510) 290-4520",
    email: "geologicaldesign@aol.com",
    billingAdress: "7719 Oakport Street\nOakland California",
  },
  {
    name: "Gladys Ruiz",
  },
  {
    name: "Gold Star Logistics Inc.",
    phoneNumber: "Mobile: 4082302613",
    email: "goldstar11100@gmail.com",
    billingAdress: "1327 Shoreview CT.\r\n,\nSan Jose CA 95122",
    shippingAdress:
      "Gold Star Logistics Inc.\r\n1327 Shoreview CT.\r\nSan Jose , CA 95122",
  },
  {
    name: "GORA TRUCKING",
    email: "asaptransportation@outlook.com",
  },
  {
    name: "GPM Trucking Corp",
    phoneNumber: "Phone: 5104539907",
    email: "gpmtrucking@yahoo.com",
    fullName: "Stephanie",
    billingAdress: "2644 Appian Way Suite # 202\r\nCalifornia\nPinole CA 94564",
    shippingAdress:
      "GPM Trucking Corp\r\n2644 Appian Way Suite # 202\r\nPinole, CA 94564\r\nUSA",
  },
  {
    name: "GSC Logistics, Inc.",
    phoneNumber: "Mobile: (650) 281-1938",
    email:
      "APAdvice@gsclogistics.com, Compliance@gsclogistics.com, imiller@gsclogistics.com",
    billingAdress: "530 Water Street, 5th Floor\nOakland CA 94607",
    shippingAdress:
      "GSC Logistics, Inc.\n530 Water Street, 5th Floor\nOakland, CA 94607\nUSA",
  },
  {
    name: "Harmun Trucking Inc",
    phoneNumber: "Mobile: 5308706016",
    email: "harmuntrucking@hotmail.com",
    fullName: "Mr. Harmun",
    billingAdress: "3450 Industrial Dr.\nYuba City CA 95993",
    shippingAdress:
      "Harmun Trucking Inc\r\n3450 Industrial Dr.\r\nYuba City, CA 95993",
  },
  {
    name: "Hawaiian Ocean Transport",
    phoneNumber: "Mobile: (510) 755-7712",
    email: "Crawfordm@americanfast.com",
    fullName: "Mark Crawford",
    billingAdress:
      "2968 Alvarado St.\nSuite A\nSan Leandro California 94577\nUSA",
    shippingAdress:
      "2968 Alvarado St.\nSuite A\nSan Leandro California 94577\nUSA",
  },
  {
    name: "Hayward Office",
    fullName: "Hayward Office",
  },
  {
    name: "Henean Trucking",
    phoneNumber: "Phone: 4159138674",
    email: "archilatrucking@gmail.com",
    fullName: "Jhonatan",
    billingAdress: "Henean trucking\r\n14000 gracebee ave\nnorwalk CA 90650",
  },
  {
    name: "hennessy",
  },
  {
    name: "Henry Boyajian Inc.",
    email: "hboyajian@aol.com",
  },
  {
    name: "Hi Touch Machinery",
    phoneNumber: "Phone: 5108287728",
    email: "bukjeff@yahoo.com",
    fullName: "Jeffry",
    billingAdress: "HI",
  },
  {
    name: "HWY911 INC",
    phoneNumber: "Mobile: (510) 304-0196",
    email: "hwy911inc@gmail.com",
    billingAdress: "105 Fernwood Dr.\nSan Bruno California 94066\nUSA",
  },
  {
    name: "Immortal Trucking",
    phoneNumber: " (510) 456-8814",
    email: "accounting@immortaltrucking.com",
    fullName: "Gurjap",
    billingAdress:
      "15882 Covered Bridge Way\nLathrop California 95330\nUnited States",
    shippingAdress:
      "15882 Covered Bridge Way\nLathrop California 95330\nUnited States",
  },
  {
    name: "Industrial Drayage",
    email: "Berkwhse@earthlink.net",
    fullName: "Industrial Drayage",
    billingAdress: "PO Box 7706\nBerkeley California 94707\nUSA",
    shippingAdress: "PO Box 7706\nBerkeley California 94707\nUSA",
  },
  {
    name: "Integrated Concrete Construction",
    phoneNumber: "\nMobile: 5105894209",
    email: "ap@integrated-concrete.com",
  },
  {
    name: "Integrated Transportation Company",
    email: "ap@integrated-concrete.com",
    fullName: "Walter Catalan",
    billingAdress: "3530 Depot Rd.\nHayward CA 94546",
    shippingAdress: "3530 Depot Rd.\nHayward CA 94546",
  },
  {
    name: "Inter Global Logistics",
    phoneNumber: "\nMobile: 5107723611",
    email: "gabriel@iglautoshipping.com, xcunich@yahoo.com",
    fullName: "Mr. Gabriel Cunish",
    billingAdress: "1930 Fairway Dr.\nSan Leandro CA 94577",
    shippingAdress: "Gabriel Cunish\n1930 Fairway Dr.\nSan Leandro CA 94577",
  },
  {
    name: "Inter Pacific Transport",
    phoneNumber: "\nMobile: 925 305 8270",
    email: "pmatic925@aol.com",
    fullName: "Mr. Jose Ortiz",
    billingAdress: "P.O BOX 7554\r\n,\nOakland CA 94601",
    shippingAdress:
      "Inter Pacific Transport\r\nMr. Jose Ortiz\r\nP.O BOX 7554\r\nOakland , CA 94601",
  },
  {
    name: "Iraheta Bros 2 Inc",
    phoneNumber: "Phone: 5103426703",
    email: "operations@irahetabros.com",
    fullName: "Nelson Iraheta",
    billingAdress:
      "Iraheta Bros 2 Inc.\r\n125 Second St. Suite 513\r\n,\nOakland CA 94607",
  },
  {
    name: "J & S DRAYAGE",
    phoneNumber: "\nMobile: 5107547643",
    email: "dispatch@jsdrayage.com",
    fullName: "Sam",
    billingAdress:
      "J&S Drayage, LLC\r\n7700 EdgeWater Drive, STE# 524\nOakland CA 94621",
  },
  {
    name: "JAGDIP S GIL",
    phoneNumber: "Phone: (510) 314-1280",
    fullName: "JAGDIP S GIL",
  },
  {
    name: "JASON STEVE HERRERA",
    email: "victormorales323@gmail.com",
  },
  {
    name: "JB Hunt",
    email: "Chris.Mathewson@jbhunt.com",
    billingAdress: "28701 Hall Rd.\nHayward CA 94545",
  },
  {
    name: "JC Trucking",
    email: "jctruckschool@gmail.com",
  },
  {
    name: "Jellison Trucking",
    phoneNumber: "Mobile: (641) 216-3320",
    email: "mlj61@live.com",
    fullName: "Jellison Trucking",
    billingAdress: "339 N. 6th Street\nSeymour Iowa 52590\nUSA",
    shippingAdress: "339 N. 6th Street\nSeymour Iowa 52590\nUSA",
  },
  {
    name: "Jorge  Alberto Martinez",
    phoneNumber: "Mobile: (510) 706-4224",
    email: "jmartinez4468@hotmail.com",
    fullName: "Jorge Alberto Martinez",
  },
  {
    name: "Judge Trucking",
    phoneNumber: "Mobile: 5107133721",
    email: "avtarj@sbcglobal.net",
  },
  {
    name: "Kamal Trucking Corporation",
    phoneNumber: "Phone: 510 451-5034",
    email: "ron@kamaltrucking.com",
    fullName: "Kamal Boushehri",
    billingAdress: "P.O Box 23784\nOakland CA 94623",
    shippingAdress: "P.O Box 23784\nOakland CA 94623",
  },
  {
    name: "Knight Transportation",
    phoneNumber: " chris 1000061805",
    email: "rrrt@knighttrans.com",
    billingAdress: "20002 N. 19th Ave\nPhoenix Arizona 85027\nUSA",
  },
  {
    name: "KS Trans Inc.",
    phoneNumber: "Phone: (925) 200-1448",
    email: "calibaywater@yahoo.com",
    fullName: "Singh",
    billingAdress: "1214 north p st \nlivermore Ca 94551",
  },
  {
    name: "KVM Transport LLC",
    phoneNumber: "Mobile: (510) 301-3251",
    email: "KVMT@me.com",
    fullName: "Kenneth Spencer",
    billingAdress: "2295 Tilgrin Way\nHayward California\nUSA",
    shippingAdress: "465 Roland Way\nOakland California\nUSA",
  },
  {
    name: "L trans Driver",
  },
  {
    name: "L TRANS INC",
    phoneNumber: "\nMobile: 9255756093",
    email: "Ltransinc@yahoo.com, rosie_ltransinc@yahoo.com",
    fullName: "Lili",
    billingAdress:
      "1155 Third St\r\nSuite # 206\r\nCalifornia\nOakland CA 94607\nUSA",
    shippingAdress:
      "L TRANS INC\r\n1155 Third St\r\nSuite # 206\r\nOakland, CA 94607\r\nUSA",
  },
  {
    name: "Lakin Tire",
    phoneNumber: "\nMobile: (562) 668-4382",
    email: "ap@lakintire.com,lalcala@lakintire.com",
    billingAdress:
      "600 River Avenue , 3rd Floor\nPittsburgh Pensilvania 15212\nUSA",
    shippingAdress:
      "600 River Avenue , 3rd Floor\nPittsburgh Pensilvania 15212\nUSA",
  },
  {
    name: "LARRY TRUCKING",
    phoneNumber: "\nMobile: 5108812222",
    email: "larrytruckingcorp@yahoo.com",
    fullName: "Larry",
    billingAdress: "15738 Paseo Larga Vista\nSan Lorenzo CA 94580",
    shippingAdress:
      "LARRY TRUCKING CORPORATION\r\n15738 Paseo Larga Vista\r\nSan Lorenzo, CA 94580",
  },
  {
    name: "LDT Transport Inc.",
    phoneNumber: "\nMobile: (916) 849-1142",
    email: "ldt.trans@gmail.com",
    fullName: "greg",
    billingAdress: "7700 edgewater drive, Ste# 524,\r\nCa\nOakland CA 94621",
  },
  {
    name: "LEALS TRANSPORTATION",
    phoneNumber: "Phone: (661) 426-3293",
    email: "leals16ts@gmail.com",
    fullName: "LEALS TRANSPORTATION",
  },
  {
    name: "Lineage",
    phoneNumber: "Phone: 9099535230",
    email: "csilveira@lineagelogistics.com",
    billingAdress: "21700 Barton Rd.\nColton CA",
    shippingAdress: "21700 Barton Rd.\nColton CA",
  },
  {
    name: "Lineage Logistics",
    phoneNumber: "Phone: (510) 407-4384",
    email: "gduke@lineagelogistics.com,shcampbell@lineagelogistics.com",
    billingAdress: "San Leandro California",
    shippingAdress: "San Leandro California",
  },
  {
    name: "Macy's Logistics  - Hayward",
    phoneNumber: "Mobile: (510) 887-7333",
    email: "debbie.caires@macys.com,Expinvoice@macys.com",
    billingAdress:
      "Debbie.caires@macys.com\n\n28701 Hall Road\nHayward California 94546\nUSA",
    shippingAdress: "28701 Hall Road\nHayward California 94546\nUSA",
  },
  {
    name: "Macy's Logistics  - Union City",
    phoneNumber: "510.441.8833 ext.3506",
    email: "debbie.caires@macys.com,Expinvoice@macys.com",
    billingAdress:
      "Debbie.Caires@macys.com\n1200 Whipple Road\nUnion City California 94587\nUSA",
    shippingAdress:
      "Debbie.Caires@macys.com\n1200 Whipple Road\nUnion City California 94587\nUSA",
  },
  {
    name: "Managed Facilities Solutions, LLC",
    phoneNumber: "Mobile: (408) 717-0425",
    email: "isaac@mfs.team,ap@mfs.team",
    billingAdress: "128 Component Drive\nSan Jose California 95131\nUSA",
    shippingAdress: "128 Component Drive\nSan Jose California 95131\nUSA",
  },
  {
    name: "Mand Trucking",
    phoneNumber: "Mobile: 4084550310",
    email: "kuldip_mand@yahoo.com",
    billingAdress: "194 Ridgeview Dr.\nTracy CA 95377",
    shippingAdress: "Mand Trucking\r\n194 Ridgeview Dr.\r\nTracy, CA 95377",
  },
  {
    name: "mantrans",
    email: "terrisnyder@live.com",
  },
  {
    name: "Marquez Transport",
    phoneNumber: "Mobile: 8189683765",
    email: "transport.marquez@gmail.com",
    billingAdress: "17505 Haynes St.\nVan Nuys CA 91409",
    shippingAdress: "17505 Haynes St.\nVan Nuys CA 91409",
  },
  {
    name: "Mashhoor Alam",
  },
  {
    name: "MasterFleet National LLC,",
    phoneNumber: " (920) 347-3513\n",
    email: "Payment@mfnatl.com, accounting@mfnatl.com",
    billingAdress: "PO BOX 5669\nDe Pere Wisconsin 54115\nUSA",
  },
  {
    name: "MC KINNEY - Hayward",
    phoneNumber: "Phone: 510-471-1700",
    email: "ivinerts@mckinneytrailers.com,dlopez@mckinneytrailers.com",
    billingAdress: "30000 Industrial Parkway SW\nHayward CA 94544",
    shippingAdress: "30000 Industrial Parkway SW\nHayward CA 94544",
  },
  {
    name: "MC Kinney - Stockton",
    phoneNumber: "Mobile: (209) 993-5133",
    email: "gdecker@mckinneytrailers.com",
    fullName: "Greg Decker",
    billingAdress: "1021 S Stockton St\nStockton California 95203\nUSA",
    shippingAdress: "1021 S Stockton St\nStockton California 95203\nUSA",
  },
  {
    name: "mc transportation",
    phoneNumber: "Phone: 916-6487430",
    email: "OFFICE@MCTRANS.US",
    fullName: "mike",
  },
  {
    name: "Men at Work Transportation Inc",
    phoneNumber: "Mobile: 2092074605",
    email: "menatworktrans@hotmail.com",
    fullName: "Mr Carlos Balines",
    billingAdress:
      "Mr. Carlos Balines\n651 South 32nd Street\nRichmond CA 94804",
    shippingAdress:
      "Mr. Carlos Balines\n651 South 32nd Street\nRichmond CA 94804",
  },
  {
    name: "Merchants Fleet Management",
    phoneNumber: "Phone: (877) 870-4999",
    email: "fmfaxcreditcard@merchantsfleet.com",
    billingAdress:
      "PO Box 16415\n1278 Hooksett Road\nHooksett New Hampshire 03106\nUSA",
  },
  {
    name: "Milestone Trailer Leasing",
    phoneNumber: "Phone: (209) 645-5104",
    email:
      "stockton@milecorp.com ,trevor.fairley@milecorp.com,curtis.pollitt@milecorp.com",
    billingAdress: "3711 Producers Dr.\nStockton California 95206\nUSA",
    shippingAdress: "3711 Producers Dr.\nStockton California 95206\nUSA",
  },
  {
    name: 'MING"S RESOURCE EAST BAY CORP',
    phoneNumber: "Mobile: (510) 570-0198",
    email: "lisa@mingsrecycling.com",
    billingAdress: "3495 Breakwater Court\nHayward california 94545\nUSA",
    shippingAdress: "3495 Breakwater Court\nHayward california 94545\nUSA",
  },
  {
    name: "MINI MOBILE",
    email: "kevans@mobilemini.com",
    fullName: "MINI MOBILE",
    billingAdress: "44580 old warm spring blvd\nfremont ca 94538",
    shippingAdress: "44580 old warm spring blvd\nfremont ca 94538",
  },
  {
    name: "Momentum Battery & Lift Truck Solutions",
    phoneNumber: "Mobile: (925) 348-4887",
    email: "momentumbatterysolutions@gmail.com",
    fullName: "Jenny",
    billingAdress: "1098 Mitchell Canyon Road\nClayton California 94517\nUSA",
    shippingAdress: "1098 Mitchell Canyon Road\nClayton California 94517\nUSA",
  },
  {
    name: "MS International Inc",
    phoneNumber: " (510) 305-0810",
    email: "chad@msistone.com",
    fullName: "Chad Connery",
    billingAdress: "22300 B Hathaway Ave.\nHayward California 94541\nUSA",
  },
  {
    name: "MUTUAL",
    phoneNumber: "Phone: 5104651711",
    email: "hiko@mutualexpress.com",
    fullName: "Mr. Hiko Shimamoto",
    billingAdress: "1700 West Grand Ave.\nOakland CA 94607",
    shippingAdress: "1700 West Grand Ave.\nOakland CA 94607",
  },
  {
    name: "Narayan's Trucking Inc",
    phoneNumber: "Phone: 9163728200",
    email: "NARAYANSTRKG@SBCGLOBAL.NET",
    billingAdress: "551 Sutter Avenue\nWest Sacramento CA 95691",
    shippingAdress:
      "Narayan's Trucking Inc\r\n551 Sutter Avenue\r\nWest Sacramento, CA 95691",
  },
  {
    name: "Narrow Road Trucking",
    phoneNumber: "Mobile: 5108755562",
    email: "narrowroadtrucking@att.net",
    fullName: "Mr. Oscar",
    billingAdress: "4426 Virginia Ave.\nOakland CA 94619",
    shippingAdress: "4426 Virginia Ave.\nOakland CA 94619",
  },
  {
    name: "national recycling",
    phoneNumber: "\n (510) 882-2885",
    email: "NRC868@sbcglobal.net",
    fullName: "Richard Wang",
    billingAdress: "1312 Kirkham St\nOakland CA 946072257\nUSA",
  },
  {
    name: "natural",
    phoneNumber: "Phone: 4082358660",
    email: "stoppekw@airproducts.com",
    fullName: "Kevin Stopper",
    billingAdress: "1375 Norman Ave.\nSanta Clara CA 95054",
    shippingAdress: "1375 Norman Ave.\nSanta Clara CA 95054",
  },
  {
    name: "Natural Logistics",
    email: "natural_logistics@live.com",
  },
  {
    name: "Nettee Ford",
    phoneNumber: "Phone: (510) 459-0225",
    email: "afordtrucking2@gmail.com,",
    fullName: "Nettee Ford",
    billingAdress: "1951 - B Fairway Drive\nSan Leandro California 94577\nUSA",
    shippingAdress: "1951 - B Fairway Drive\nSan Leandro California 94577\nUSA",
  },
  {
    name: "Newport  Carriers Inc",
    phoneNumber: "\nMobile: 5107060173",
    email: "portcarriers@gmail.com",
    billingAdress: "32646 ENDEAVOUR WAY\nUNION CITY CA 94587\nUSA",
  },
  {
    name: "North America  3PL",
    phoneNumber: "Phone: 510 972 9880",
    email: "warehouse@na3pl.com, ces@na3pl.com",
    fullName: "Jorge",
    billingAdress: "1700 - 20th Street\nOakland CA 94607",
    shippingAdress: "1700 - 20th Street\nOakland CA 94607",
  },
  {
    name: "OA EXPRESS",
    phoneNumber: "Mobile: 5038385316",
    email: "All@OAExpress.com,christina.sharp@oaexpress.com",
    billingAdress: "OA Express 2222 East Beamer St. Woodland,",
  },
  {
    name: "OAKLAND PORT TRUCKING, LLC.",
    email: "oaklandporttk@gmail.com",
  },
  {
    name: "Ocean Rail Logistics Inc.",
    phoneNumber: "Phone: 5106571600",
    email: "dispatch@orlogistics.com",
    fullName: "gil",
    billingAdress: "46560 Fremont Blvd\nSuite # 306\nFremont CA 94538",
    shippingAdress: "46560 Fremont Blvd\nSuite # 306\nFremont CA 94538",
  },
  {
    name: "Odyssey FoodTrans LLC",
    phoneNumber: "\nMobile: 2095184222",
    email: "MarissaLoffler@odysseylogistics.com,Miketran@odysseylogistics.com",
    billingAdress: "2 Park Plaza , Suite # 525\nIrvine California 924614\nUSA",
    shippingAdress: "Hayward\nHayward California\nUSA",
  },
  {
    name: "Pacific Agri-Products, Inc.",
    phoneNumber: "Phone: (650) 873-0440",
    email: "jmar@pacagri.com",
    fullName: "Pacific Agri-Products, Inc.",
    billingAdress: "477 Forbes Blvd\nSouth San Francisco California 94080\nUSA",
    shippingAdress:
      "477 Forbes Blvd\nSouth San Francisco California 94080\nUSA",
  },
  {
    name: "Pacific Coast Container  7th Street - Division 01",
    phoneNumber: " (510)545-7565  Jorge",
    email: "apinvoices@pcclogistics.com",
    billingAdress: "2099 7th Street\nOakland California 94607\nUSA",
    shippingAdress: "2099 7th Street\nOakland California 94607\nUSA",
  },
  {
    name: "Pacific Cycle Inc",
    phoneNumber: "\nMobile: 7078631993",
    email: "lpapalii@pacific-cycle.com",
    fullName: "Liz",
    billingAdress: "2041 Cessna Drive\r\n california\nVacaville CA 95687",
    shippingAdress: "Pacific Cycle Inc\r\n2041 Cessna Drive\r\nVacaville.95687",
  },
  {
    name: "Pacific Drayage Services",
    phoneNumber: " (925) 493-6481\n",
    email: "sagee@pdsusa.com,jcuellar@pdsusa.com",
    billingAdress:
      "757 East 11th Street, Suite 103\nTracy California 95376\nUSA",
    shippingAdress:
      "757 East 11th Street, Suite 103\nTracy California 95376\nUSA",
  },
  {
    name: "PACIFIC RIM RECYCLING",
    phoneNumber: "Mobile: 6503020700",
    email: "brandenkirschenman@gmail.com",
    fullName: "Mr Branden Kirschenman",
    billingAdress: "3690 Spring Drive\r\nCa\nBenicia CA 94510",
    shippingAdress:
      "PACIFIC RIM RECYCLING\r\n3690 Spring Drive\r\nBenicia, CA 94510",
  },
  {
    name: "Pacific Transload System - Division 14",
    phoneNumber: "Mobile: 5107735232",
    email: "apinvoices@pcclogistics.com,dave@pcc.cc",
    billingAdress: "737  Bay St.\nCalifornia\nOakland CA 94607\nUSA",
    shippingAdress: "737  Bay St.\nCalifornia\nOakland CA 94607\nUSA",
  },
  {
    name: "Palo alto fine wine & spirits",
    phoneNumber: "Phone: (650) 494-3640",
    billingAdress: "3163 middlefield road\npalo alto ca 94306",
    shippingAdress: "3163 middlefield road\npalo alto ca 94306",
  },
  {
    name: "PCC - Direct Delivery Division 05",
    email: "Raul@pcc.cc,Dominick@pcclogistics.com,apinvoices@pcclogistics.com",
    billingAdress: "2498 West 16th Street\nBuilding 803\nOakland CA 94607\nUSA",
    shippingAdress:
      "Pacific Coast Container\n2498 West 16th Street\nBuilding 803\nOakland, CA 94607\nUSA",
  },
  {
    name: "PCC Corporate",
    email: "rosa@pcc.cc,ejerez@pccsw.com",
    billingAdress: "432 Estudillo Ave.\nSan Leandro California 94580\nUSA",
    shippingAdress: "432 Estudillo Ave.\nSan Leandro California 94580\nUSA",
  },
  {
    name: "PCC Logistics - Division 09",
    phoneNumber: "Mobile: 510 7736568",
    email:
      "jlara@pcc.cc,Stephanie@pcclogistics.com,Luis@pcclogistics.com,apinvoices@pcclogistics.com",
    billingAdress: "2498 West 16th Street\nBuilding 803\nOakland CA 94607\nUSA",
    shippingAdress:
      "PCC LOGISTICS\n2498 West 16th Street\nBuilding 803\nOakland, CA 94607\nUSA",
  },
  {
    name: "Penske 24/7 Roadside Assistance",
    phoneNumber: "(855) 234-0013  ",
    email: "penskesosinvoices@penske.com",
    billingAdress:
      "2675 Morgantown Road\nReading Pennsylvania 19607\nUSA    Vendor # 1017677",
    shippingAdress: "California\nUSA",
  },
  {
    name: "Penske Fleet Management 6990-10",
    phoneNumber: "Phone: (855) 234-0016",
    email: "PFMFleet@penske.com,pfminvoices@penske.com",
    billingAdress: "2675 Morgantown Rd\nReading Pennsylvania 19607\nUSA",
    shippingAdress: "California",
  },
  {
    name: "Pinnacle Ag. Services",
    phoneNumber: "Mobile: 2096526196",
    email: "sbaker@cvagtransport.com",
    fullName: "Scott Baker",
  },
  {
    name: "Preferred Freezer Services",
    phoneNumber: "\nMobile: 732496 4877",
    email:
      "pabdilla@pfsl.com, szicarelli@preferredfreezer.com, vbaez@preferredfreezer.com",
    fullName: "Mr. Paul Abdilla",
    billingAdress: "400 Hudson Lane\nSan Leandro CA 94577",
  },
  {
    name: "Progressive Transportation Services, LLC",
    phoneNumber: " 3106842121 rene",
    email: "Accounts_Payable@imcc.com,tmathis@imcc.com",
    billingAdress: "750 Maritime St.\nOakland CA 94607",
    shippingAdress:
      "Progressive Transportation Services, LLC\r\n750 Maritime St.\r\nOakland, CA 94607",
  },
  {
    name: "Quik Pick Express",
    phoneNumber: "Mobile: (510) 225-5205",
    email:
      "shutchins@quikpickexpress.com,mmeda@quikpickexpress.com,PAndrade@quikpickexpress.com",
    billingAdress: "8707 San Leandro Blvd\nOakland California 94621\nUSA",
    shippingAdress: "8707 San Leandro Blvd\nOakland California 94621\nUSA",
  },
  {
    name: "Quik Pick Express, LLC",
    phoneNumber: "Mobile: (510) 225-5205",
    email:
      "jmoro@quikpickexpress.com,ap@quikpickexpress.com,mmeda@quikpickexpress.com",
    billingAdress: "8707 San Leandro Blvd\nOakland California 94621\nUSA",
    shippingAdress: "8707 San Leandro Blvd\nOakland California 94621\nUSA",
  },
  {
    name: "RARA Trucking",
    phoneNumber: "Mobile: (408) 422-3861",
    email: "rara_trucking@yahoo.com",
    fullName: "Raul",
    billingAdress: "1488 Mabury Rd.\nSan Jose California 95133\nUSA",
  },
  {
    name: "RAYCO",
    phoneNumber: "Phone: 5105383667\n",
    billingAdress: "2516 san carlos ave\ncastro valley CA 94546",
    shippingAdress: "2516 san carlos ave\ncastro valley CA 94546",
  },
  {
    name: "RDX INC.",
    phoneNumber: "Mobile: (559) 801-6163",
    email: "paul@rdxinc.org,pdeleon@rdxinc.org",
    fullName: "Paul",
    billingAdress: "2436 S. Sarah St.\nFresno CA 93706",
    shippingAdress: "RDX INC\r\n2436 S. Sarah St.\r\nFresno, CA 93706",
  },
  {
    name: "Replanet LLC",
    phoneNumber: "Phone: 9093680100 ext",
    email: "victor.morales@replanet.com",
    fullName: "Mr Victor Morales",
    billingAdress: "800 N Haven  Ave. # 120\nOntario CA CA 91764",
    shippingAdress: "800 N Haven  Ave. # 120\nOntario CA CA 91764",
  },
  {
    name: "Republic Transportation",
    phoneNumber: "Phone: (626) 712-3990",
    email: "BILLING@REPUBLICTRANSPORTCO.COM",
    fullName: "Adolf",
    billingAdress: "351 S Irwindale Ave\nAzusa California 91702\nUSA",
  },
  {
    name: "ricardo Rodrigues",
  },
  {
    name: "Richard  Wang",
    phoneNumber: "Mobile: (510) 882-2885",
    email: "nrc868@sbcglobal.net",
    fullName: "Richard Wang",
    billingAdress: "1312 Kirkham St\nOakland CA 94607\nUSA",
    shippingAdress: "1312 Kirkham St\nOakland CA 94607\nUSA",
  },
  {
    name: "RJJ Resource",
    phoneNumber: "Phone: 4088581628",
    email: "purchaserjjresource@gmail.com",
    fullName: "Mr. Kevin",
    billingAdress: "1411 Harbour Way south\nRichmond",
    shippingAdress: "RJJ Resource\r\n1411 Harbour Way south\r\nRichmond",
  },
  {
    name: "RJS ASSOCIATES",
  },
  {
    name: "ROAD  EX LOGISTICS, INC",
    phoneNumber: "Phone: 5102267400",
    email: "dispatch@orlogistics.com",
    billingAdress: "46560 Fremont Blvd STE 306\nFremont CA 94538",
    shippingAdress: "46560 Fremont Blvd STE 306\nFremont CA 94538",
  },
  {
    name: "Roadex America Inc",
    phoneNumber: "\nMobile: 310 293 6696",
    email: "derek.wong@roadexamerica.com,ap@roadexamerica.com",
    fullName: "Mr Derek Wong",
    billingAdress:
      "Mr. Derek Wong\r\n1515 West  178th Street\nGardena CA 90248",
    shippingAdress:
      "Roadex America Inc\r\nMr. Derek Wong\r\n1515 West  178th Street\r\nGardena, CA 90248",
  },
  {
    name: "ROADNET EXPRESS",
    phoneNumber: "Phone: 5107556763",
    email: "roadnetlogistics@gmail.com",
    billingAdress: "37338 Fowler St\nNewark CA 94560",
    shippingAdress: "37338 Fowler St\nNewark CA 94560",
  },
  {
    name: "Robertos's Truck Repair",
    email: "beckyrod005@gmail.com",
  },
  {
    name: "ROBLES TRUCKING",
    fullName: "ARTURO",
    billingAdress: "1511 MT. EVEREST CT\r\nCALIFORNIA\nSAN JOSE CA 95127\nUSA",
  },
  {
    name: "Rocha Transportation",
    phoneNumber: "Phone: 2095544119\nMobile: 2094561192",
    email: "granth@rochatrans.com",
    fullName: "Grant Hannink",
    billingAdress: "2400 Nicholson\nModesto CA 94358",
    shippingAdress: "2400 Nicholson\nModesto CA 94358",
  },
  {
    name: "Rock-N-4 Trucking",
    phoneNumber: "Mobile: (408) 569-2658",
    email: "raragon@rockn4.com",
    fullName: "Ronald Aragon",
    billingAdress: "1501 Decoto Rd\nUnion City California 94587\nUSA",
    shippingAdress: "1501 Decoto Rd\nUnion City California 94587\nUSA",
  },
  {
    name: "Royal Line - Jesus",
    phoneNumber: "Phone: 8058298612",
    email: "royalline@earthlink.net",
    fullName: "Jesus Magaña",
    billingAdress: "California\nLamont CA 93241\nUSA",
  },
  {
    name: "RVidal Trucking",
    phoneNumber: "\nMobile: (707) 704-4933",
    email: "rvtdispatch@rvidaltrucking.com",
    fullName: "Erick Mendoza",
    billingAdress: "411 Main Street Suite G\nSuisun California 94585\nUSA",
    shippingAdress: "411 Main Street Suite G\nSuisun California 94585\nUSA",
  },
  {
    name: "S F  Enterprises & Logistics, LLC",
    phoneNumber: "\nFax: 510 251-2148",
    email: "felise@sfenterprises.net",
    fullName: "Mr. Felise Langi",
    billingAdress: "2525 Mandela Pkwy\nOakland CA 94607",
    shippingAdress:
      "S.F. Enterprises & Logistics, LLC\r\n2525 Mandela Pkwy\r\nOakland, CA 94607",
  },
  {
    name: "S G Transport",
    phoneNumber: "\nMobile: (510) 789-9565",
    email: "sukhsgtransport@gmail.com",
    fullName: "Sukh Ghumann",
  },
  {
    name: "Sabine Andreini",
    fullName: "Sabine Andreini",
    billingAdress: "1716 Ralston Avenue\nBurlingame California 94010\nUSA",
    shippingAdress: "1716 Ralston Avenue\nBurlingame California 94010\nUSA",
  },
  {
    name: "Santos Pocasangre",
    phoneNumber: "Phone: 5106899564",
    billingAdress: "1418  78th Ave.\nOakland CA 94621",
    shippingAdress: "1418  78th Ave.\nOakland CA 94621",
  },
  {
    name: "Scoutt",
    phoneNumber: "Mobile: (707) 479-8690",
    email: "iscoutt@gmail.com",
    billingAdress: "Po Box 2533\nSausalito California 94966\nUSA",
    shippingAdress: "Po Box 2533\nSausalito California 94966\nUSA",
  },
  {
    name: "SEA ROAD TRANSPORTATION INC.",
    phoneNumber: "Mobile: (510) 344-8584",
    email: "dispatch@searoadtrans.com",
    billingAdress: "35868 Killorglin Common\nFremont California 94536\nUSA",
    shippingAdress: "35868 Killorglin Common\nFremont California 94536\nUSA",
  },
  {
    name: "Second Harvest of Silicon Valley",
    phoneNumber: "Mobile: (408) 627-3881",
    email: "acastellanos@shfb.org,jhandforth@shfb.org",
    billingAdress: "750 Curtner Avenue\nSan Jose california 95125\nUSA",
    shippingAdress: "750 Curtner Avenue\nSan Jose california 95125\nUSA",
  },
  {
    name: "SGS TRANSPORTATION",
    phoneNumber: "Mobile: (510) 931-0795",
    email: "francisco.sgs@outlook.com",
    fullName: "Francisco Martinez",
    billingAdress:
      "2600 Central Ave. Suite D\nUnion City California 94587\nUSA",
  },
  {
    name: "Shacheen Trans LLC",
  },
  {
    name: "Shipper Transport",
    phoneNumber: "Mobile: 5103841017",
    email: "Guy.Sanderson@shipperstransport.com",
    fullName: "Guy Sanderson",
    billingAdress:
      "555 B Maritime St\r\nCalifornia \r\nVendor #418834\nOakland CA 94607\nUSA",
    shippingAdress:
      "SHIPPER TRANSPORT EXPRESS\r\n555 B Maritime St\r\nOakland, California 94607\r\nUSA\r\nVendor # 418834",
  },
  {
    name: "Silva Trucking Inc & Stockton Ag Transpor",
    phoneNumber: "Mobile: 2099932253",
    email: "ap@silvatrucking.com",
    fullName: "Cindy Hoeksema",
    billingAdress:
      "36 West Mathews Road\nCalifornia\nFrench Camp CA 95231\nUSA",
    shippingAdress:
      "36 West Mathews Road\nCalifornia\nFrench Camp CA 95231\nUSA",
  },
  {
    name: "Singh Transport INC.",
    phoneNumber: "\nMobile: 5105433778",
    email: "singhtransportinc@gmail.com",
    billingAdress:
      "401 roland way suite 224\noakland ca 94621\nEmeryville CA 94604",
    shippingAdress:
      "Singh Transport  INC\n401 roland way suite 224\nOakland Ca 94621",
  },
  {
    name: "Smart Cycle Hauling",
    phoneNumber: " 408-600-9561 - JIM",
    email: "ops@smartcyclehauling.com",
    fullName: "Smart Cycle Hauling",
    billingAdress: "3495 Breakwater Ave\nHayward CA 94545",
    shippingAdress: "3495 Breakwater Ave\nHayward CA 94545",
  },
  {
    name: "smooth ride transport LLC",
  },
  {
    name: "SP BROSS TRUCKING",
    email: "spbrostruck@gmail.com",
    billingAdress:
      "5214 F DIAMOND HEIGHT\r\nSUITE 814\nSAN FRANCISCO CA 94131\nUSA",
  },
  {
    name: "SPEEDO FREIGHT SYSTEM, INC.",
    email: "INFO@SPEEDOFRE.COM",
  },
  {
    name: "STAR  TRANSPORT, LLC",
    phoneNumber: "Mobile: 559 318-7056",
    email: "jennifer@startransport.net",
    billingAdress: "9400 S. De Wolf Avenue\nSelma CA 93662",
    shippingAdress:
      "STAR  TRANSPORT, LLC\r\nMrs. Brittany M. Westbrook\r\n9400 S. De Wolf Avenue\r\nSelma, CA 93662",
  },
  {
    name: "Steve Lindridge",
    phoneNumber: "Phone: (910) 985-1122",
    email: "slindridge@ctccontract.com",
    fullName: "Steve Lindridge",
    billingAdress: "99 Mosely Ave.\nAlameda California 94501\nUSA",
    shippingAdress: "99 Mosely Ave.\nAlameda California 94501\nUSA",
  },
  {
    name: "STG LOGISTICS",
    phoneNumber: "Phone: (510) 597-2182",
    email: "stgapinvoices@stgusa.com",
    billingAdress: "5165 EMERALD PARKWAY\nSUITE 300\nDUBLIN OH 43017",
  },
  {
    name: "Stockmyer Trucking Inc",
    phoneNumber: "\nMobile: (530) 787-3002",
    email: "dispatch@stockmyertrucking.com",
    fullName: "Kara Holland",
  },
  {
    name: "Sun LongExpress Inc",
    phoneNumber: "\nMobile: (510) 455-6603",
    email: "jerry@sunlongexpress.com,info@sunlongexpress.com",
    fullName: "Jerry Fok",
    billingAdress: "496 Hester Street\nSan Leandro California 94577\nUSA",
    shippingAdress: "496 Hester Street\nSan Leandro California 94577\nUSA",
  },
  {
    name: "super link plastic, INC.",
    email: "matty@superlinkusa.com",
    billingAdress: "P.O. BOX 43506\nOAKLAND CA 94624",
  },
  {
    name: "Sutter Transportation Inc.",
    phoneNumber: "\nMobile: 5109122083",
    email: "nameservice@suttertransportation.com",
    billingAdress: "890 Bridgeway Cir .\nel sobrante CA 94803\nUSA",
    shippingAdress:
      "S Line Transportation\nKahlon Ajaib\n780 West Grand Ave.\nOakland, CA 94612\nUSA",
  },
  {
    name: "Svt Logistics Inc.",
    phoneNumber: "\nMobile: (209) 269-9107",
    email:
      "Ana.sunvalleyoffice@gmail.com,containers@sunvalleyexpresstransport.com",
    billingAdress: "420 W Pine St Ste 9\nLodi CA 95240\nUnited States",
    shippingAdress: "Oakland  Port\nCalifornia\nUnited States",
  },
  {
    name: "Swift Transportation",
    phoneNumber: "obile: (800) 467-6017",
    email: "act_invoices@swifttrans.com",
    billingAdress: "PO Box 29244\nPhoenix AZ 85038\nUSA",
  },
  {
    name: "Tec Equipment",
    phoneNumber: "Phone: (209) 642-6230",
    email: "Mzimak@tecequipment.com",
    fullName: "Mark",
    billingAdress: "2050 East Louise\nLatrop California 95330\nUSA",
  },
  {
    name: "Tech Air/dba Alliance Welding Supplies",
    phoneNumber: "\nMobile: 5108128518",
    email: "apmail@techair.com, mdutrow@alliancegas.com",
    billingAdress:
      "Account Payable \n50 Mill Plain Road\nDambury CT 06811\nUSA",
  },
  {
    name: "Tesla Inc.",
    email: "adaray@tesla.com",
  },
  {
    name: "TGS Transportation Inc.",
    phoneNumber: "obile: 559-978-1724",
    email: "tgs-ap@tgstrans.com,jcardona@tgstrans.com",
    billingAdress:
      "T.G.S. Transportation Inc.\r\nFresno,\nPO Box 2668 CA 93745",
    shippingAdress: "Maritime St\nOakland California 94607\nUSA",
  },
  {
    name: "The Crew Trans",
    email: "thecrewtrans@gmail.com",
    fullName: "The Crew Trans",
  },
  {
    name: "The Little Giants Lighting & Grip Co.",
    phoneNumber: "Phone: (415) 626-3555",
    email: "info@littlegiantlighting.com",
    billingAdress: "3050B 23rd St.\nSan Francisco California 94110\nUSA",
  },
  {
    name: "Three Rivers Trucking Inc",
    phoneNumber: "Phone: 5104359734\n",
    email: "denise@3riverstrucking.com",
    billingAdress: "California\nOakland CA",
  },
  {
    name: "TM Demolition",
    phoneNumber: "Mobile: 4154256488",
    email: "tarcio@tmdemolition.com",
    fullName: "Mr. Tarcio Mascarenhas",
    billingAdress: "Mr.Tarcio Mascarenhas",
    shippingAdress: "TM Demolition\r\nTarcio Mascarenhas",
  },
  {
    name: "TNT Manuel",
    phoneNumber: "Phone: 2094965291",
    email: "ticasmanny@yahoo.com",
    fullName: "Manuel",
    billingAdress: "PO BOX 1248\r\nCALIFORNIA\nSALIDA CA 95368\nUSA",
    shippingAdress: "PO BOX 1248\r\nCALIFORNIA\nSALIDA CA 95368\nUSA",
  },
  {
    name: "Toucan Trucking",
    phoneNumber: "Mobile: 5104993971",
    email: "toucantrucking@yahoo.com",
    billingAdress: "2662 Alice way\nPinole CA 94564",
    shippingAdress: "2662 Alice way\nPinole CA 94564",
  },
  {
    name: "TRAC INTERMODAL",
    email: "BLOCHEL@TRACINTERMODAL.COM, AMERCADO@TRACINTERMODAL.COM",
    billingAdress: "750 College Road East\nPrinceston New Jersey 08540\nUSA",
    shippingAdress: "750 College Road East\nPrinceston New Jersey 08540\nUSA",
  },
  {
    name: "Traction Heavy Duty",
    phoneNumber: "Phone: (510) 346-5515",
    email: "Dan_Lowery@genpt.com",
    billingAdress: "Oakland,\n7305 Edgewater Dr Ste A CA 9462",
    shippingAdress: "Oakland,\n7305 Edgewater Dr Ste A CA 9462",
  },
  {
    name: "TTN Fleet Solutions",
    phoneNumber: "\nMobile: (817) 380-4267",
    email: "dispatch@ttnfleetsolutions.com, invoices@ttnfs.com",
    billingAdress: "202 Cook Street\nArgyle Texas 76224\nUSA",
    shippingAdress: "Hayward California\nUSA",
  },
  {
    name: "Ulises Ferrer",
    email: "ulisesferrer35@hotmail.com",
  },
  {
    name: "Umanzor Trucking",
    phoneNumber: "Mobile: (510) 846-4015",
    email: "umanzorp43@gmail.com",
    fullName: "Pedro",
    billingAdress: "1992 Pacific Ave.\nSan Leandro , CA 94577",
  },
  {
    name: "Unirelo",
    phoneNumber: " 510-673-5806 anil\n",
    email: "lovelace@unirelo.com",
    fullName: "Lovelace Rufus",
    billingAdress:
      "38503 Cherry St.  \nSuite  R1\nNewark California 94560\nUSA",
  },
  {
    name: "Universal Logistics Holdings Inc.",
    phoneNumber: "\nMobile: (586) 920-0100",
    email:
      "roadservice@universallogistics.com,ap@goutsi.com, map@universallogistics.com",
    billingAdress: "12755 E 9 Mile Rd\nWarren MI 48089\nUnited States",
    shippingAdress: "375 Maritime St.\nOakland California\nUnited States",
  },
  {
    name: "Valladares Trucking",
    phoneNumber: "Mobile: 5107989962",
    email: "santos1valladares@gmail.com",
    fullName: "Mr Santos A Valladares",
    billingAdress: "1115  89th  Ave.\nOakland CA 94621",
    shippingAdress: "1115  89th  Ave.\nOakland CA 94621",
  },
  {
    name: "Valley Grown Trucking",
    email: "vgtrucking15@gmail.com",
  },
  {
    name: "valley relocation and storage",
    phoneNumber: "\nMobile: (925) 766-6996",
    email: "rviramontes@valleyrelocation.com",
    fullName: "valley relocation and storage",
    billingAdress: "5000 MARSH DRIVE\nCONCORD, CA 94520",
    shippingAdress: "5000 MARSH DRIVE\nCONCORD, CA 94520",
  },
  {
    name: "Vargas Trucking",
    phoneNumber: "obile: 5105020912",
    email: "vargastransport@att.net",
    fullName: "Eduardo Vargas",
    billingAdress: "California\nPO Box 1337 Lathrop CA 95330",
    shippingAdress: "Vargas Trucking\r\nPO Box 1337 Lathrop, CA 95330",
  },
  {
    name: "VILLEDA TRANSPORTATION",
    phoneNumber: "Phone: 5108150406",
    email: "villedatrans@yahoo.com",
    fullName: "Gelio Villeda",
    billingAdress: "2700 Sargent Ave.\nSan Pablo CA 94806",
    shippingAdress: "2700 Sargent Ave.\nSan Pablo CA 94806",
  },
  {
    name: "Wings Century Trucking",
    phoneNumber: "\nMobile: 6504838680",
    email: "wingsjim@gmail.com",
    fullName: "Jim",
    billingAdress: "1288 Ferry St.\nOakland CA 94607",
    shippingAdress: "1288 Ferry St.\nOakland CA 94607",
  },
  {
    name: "WOOD TRANSPORT",
    phoneNumber: "Phone: (559) 363-8294",
    email: "jasonwood1982@yahoo.com",
    billingAdress: "WOOD TRANSPORT",
    shippingAdress: "WOOD TRANSPORT",
  },
  {
    name: "XPO Logistics -  Hayward",
    phoneNumber: "Phone: 5107857905 Ext 406-01",
    email:
      "Beatriz.Arroyo@xpo.com,Alisha.Rodriguez@xpo.com,UOSinvoices@xpo.com,Evan.OConnor@xpo.com",
    billingAdress: "2200 Claremont Ct.\nHayward CA 94545",
    shippingAdress: "2200 Claremont Ct.\nHayward California 94545\nUSA",
  },
  {
    name: "Xpo Logistics - San Jose",
    phoneNumber: "Phone: (408) 435-3876\n",
    email:
      "Edward.Ramos@xpo.com, Beatriz.Arroyo@xpo.com, Eylen.ArciaMarquez@xpo.com,USSinvoices@xpo.com",
    billingAdress: "2171 Otoole Ave\nSan Jose California 95131\nUSA",
    shippingAdress: "2171 Otoole Ave\nSan Jose California 95131\nUSA",
  },
  {
    name: "Xtra Lease Hayward",
    phoneNumber: "\nMobile: 5106700290",
    email: "hayward@xtra.com",
    billingAdress: "3600 Depot Road\nHayward CA 94545",
    shippingAdress: "3600 Depot Road\nHayward CA 94545",
  },
  {
    name: "XTRA Sacramento",
    email: "jsterry@xtra.com",
    fullName: "Jeff Terry",
    billingAdress: "601 Harbor Blvd\nSacaramento CA",
    shippingAdress: "601 Harbor Blvd\nSacaramento CA",
  },
  {
    name: "You First Express, Inc.",
    phoneNumber: "Mobile: (310) 707-5707",
    email: "luke@yfe21.com",
    fullName: "Luke Suzuki",
    billingAdress: "350 Crenshaw Blvd A206b\nTorrance 90503\nUnited States",
    shippingAdress: "350 Crenshaw Blvd A206b\nTorrance 90503\nUnited States",
  },
  {
    name: "YRC Freight",
    phoneNumber: "\n(209) 993-7946",
    email: "yrc.invoice@yrcw.com,po.invoice@yrcfreight.com",
    billingAdress:
      "APF11FEM\n1535  E. Pescadero  Ave.\nTracy California 95304\nUSA",
    shippingAdress:
      "APF11FEM\n1535  E. Pescadero  Ave.\nTracy California 95304\nUSA",
  },
  {
    name: "Zepeda and Son",
    phoneNumber: "Phone: 3106785065",
    email: "zepeda.robin@yahoo.com",
    billingAdress: "5910 Haas Ave.\nLos Angeles CA 90047",
    shippingAdress: "5910 Haas Ave.\nLos Angeles CA 90047",
  },
  {
    name: "ZIM AMERICAN INTEGRATED SHIPPING SERVICES",
    phoneNumber: "Phone: 5105433778",
    email: "valencia.mary@us.zim.com",
    fullName: "sam",
    billingAdress: "555 EAST OCEAN BLVD. SUITE 700\nLONG BEACH CA 90802",
    shippingAdress: "555 EAST OCEAN BLVD. SUITE 700\nLONG BEACH CA 90802",
  },
];

export default customer;
