const states = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Carolina del Norte",
  "Carolina del Sur",
  "Colorado",
  "Connecticut",
  "Dakota del Norte",
  "Dakota del Sur",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawái",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Luisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Misisipi",
  "Misuri",
  "Montana",
  "Nebraska",
  "Nevada",
  "Nueva Jersey",
  "Nueva York",
  "Nuevo Hampshire",
  "Nuevo México",
  "Ohio",
  "Oklahoma",
  "Oregón",
  "Pensilvania",
  "Rhode Island",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Virginia Occidental",
  "Washington",
  "Wisconsin",
  "Wyoming",
];

export default states;
